### ISSUE TITLE
Incorrect Forecast?

### ISSUE THREAD

**Issue by osyrisrblx** [mikebryant/ac-nh-turnip-prices#1]
Hi, I'm not sure if it's expected for the given ranges to be 100% accurate, but my turnip prices create 0 possible outcomes using your tool.

Buy 93
Monday AM: 115
Monday PM: ??? (Forgot to check)
Tuesday AM: 199
Tuesday PM: 215

If I enter just the "Buy" and "Monday AM" prices, I get a bunch of different outcomes, but the highest possible outcome is 186 for Tuesday AM.

**Comment by mikebryant** [comment]
In theory, yes, should be accurate. I have encountered one issue, and the site has now been updated to say this - if this is the first week you bought from Daisy Mae, then the tool will not work. It'll be fine in subsequent weeks though. Is that your situation?

**Comment by osyrisrblx** [comment]
Possibly! Last week I bought from a friend's island, not my own. Would that have the same effect?

**Comment by mikebryant** [comment]
If this is the first week you bought from your own - then yes, the tool won't handle this week. Try next week :)
