### ISSUE TITLE
Integration with price tracker

### ISSUE THREAD

**Issue by Jarvie8176** [mikebryant/ac-nh-turnip-prices#101]
Hi,

I've been working on a turnip price tracker webapp: https://kabu.wiarlawd.me/

Would it be feasible to do an integration (e.g. auto populating price data and previous week pattern)?

**Comment by peter50216** [comment]
We do support filling the prices by query params now, for example: https://turnipprophet.io/index.html?prices=91.68.104.120.140.181
The previous week pattern & first buy support are ongoing in #57 #58 #59.

**Comment by Bazzatron19** [comment]
> We do support filling the prices by query params now, for example: https://turnipprophet.io/index.html?prices=91.68.104.120.140.181
> The previous week pattern & first buy support are ongoing in #57 #58 #59.

I cannot wait for these to get merged.

**Comment by mikebryant** [comment]
Merged now :)

https://turnipprophet.io/?prices=108.95.90.86.81&first=yes&pattern=small-spike

**Comment by mikebryant** [comment]
I think this is all good now, but please poke me if you have issues :)
