### ISSUE TITLE
Please keep the data table!

### ISSUE THREAD

**Issue by kevin-cai-jiang** [mikebryant/ac-nh-turnip-prices#107]
With the addition of Turnip Calculator, I noticed that Turnip Prophet is also adding a graph to it's UI. Just wanted to mention that the table is so, so useful in addition to the graph as it provides a much stronger understanding of the data. Would hate to see it go, and thank you so much for your work!

**Comment by mikebryant** [comment]
Oh, I really like the table, I have no plans to remove it. Don't worry :)

Thanks for the kind words, I'm glad you're finding the site useful!
