### ISSUE TITLE
"peak_start is not defined" error

### ISSUE THREAD

**Issue by RLesser** [mikebryant/ac-nh-turnip-prices#110]
Started getting this error for these inputs:
First Time: Yes
Previous Pattern: Unknown
Sunday: 100
Week Prices: 43, 38, 100, 84, 150

<img width="394" alt="Screen Shot 2020-04-15 at 10 50 01 AM" src="https://user-images.githubusercontent.com/12756127/79351605-dea35980-7f06-11ea-80a4-3adb28fa9a9f.png">

**Comment by joelft** [comment]
I am also getting this error. In my case it's when loading the page with URL parameters like this `https://turnipprophet.io/index.html?prices=100.58.53.94.140.164.0.0.0.0.0.0.0`

**Comment by theRTC204** [comment]
Almost certainly related to the refactor that was merged shortly before these reports.

Investigating...

**Comment by ChiefMilesEdgeworth** [comment]
It could be here:
https://github.com/mikebryant/ac-nh-turnip-prices/blob/8f4988224596830c5c4526765ebb40bdc214426c/js/predictions.js#L165-L182

The `peak_start` variable is used in an if statement without being declared for the function on line `176`.

**Comment by peter50216** [comment]
Well that's what happen when you partially revert a PR... :facepalm: 
All my fault, I didn't check the intermediate commit that carefully.

**Comment by mikebryant** [comment]
Sorry about that!
