### ISSUE TITLE
3-digit Tuesday morning price seems to freeze the app

### ISSUE THREAD

**Issue by warmCabin** [mikebryant/ac-nh-turnip-prices#111]
This scares me.

Here's the pattern that I'm getting in my town this week:
```
Sunday buy price: --

143
128
144
75
70

```
The site keeps putting 14 instead of 144 for Tuesday morning. Then the app won't accept any new prices until I clear Tuesday morning or put a 2-digit number there.

**Comment by theRTC204** [comment]
This appears to have been related to #110 and fixed in #113.

I have tested your numbers after the fix, and things are working again.

**Comment by mikebryant** [comment]
This is looking good to me: https://turnipprophet.io/?prices=.143.128.144.75.70

Going to close, please feel free to reopen or make a new issue if you have problems :)
