### ISSUE TITLE
[Feature Proposal] Quick-Save Profiles Locally

### ISSUE THREAD

**Issue by calvinle** [mikebryant/ac-nh-turnip-prices#112]
I think it would be a nice feature to be able to make saved profiles to compare between some friend's turnip prices and patterns.
Selecting via a drop-down menu to quickly switch between. The good thing with the current state is that state is already saved onChange when inputting.

**Comment by theRTC204** [comment]
This feature request is outside the scope of this project.

From the README
> This tool is not:
> 
> A calculator for how much money you'll make
> A way to count your turnips
> **A way to store multiple people's islands**
> Something with a backend

**Comment by mikebryant** [comment]
Yes, this is out of scope - I'm not intending to have this save multiple users.

However you can now generate permalinks, and you could generate those from some other storage, like I know a few others are doing (spreadsheets etc)
