### ISSUE TITLE
Guaranteed Minimum / Potential Maximum

### ISSUE THREAD

**Issue by bitomic** [mikebryant/ac-nh-turnip-prices#117]
Yesterday, before the graph was implemented, the Guaranteed Minimum / Potential Maximum values would show the price from the date you are in (the last turnip price you introduced). Now, it shows the guaranteed minimum from the whole week, but we can not move backwards in time.

I suggest to show again the value from your current date. Nice project, btw, really appreciated!

**Comment by mikebryant** [comment]
I'm afraid you're mistaken - it's always considered the entire week (though it was also calculating things incorrectly in some cases)

I do agree with you though - we should have it only look at the future. This is already covered in #43, so I'm going to close this issue as a duplicate.

Thank you for taking the time to raise an issue though, and I'm glad you're finding the site useful :)
