### ISSUE TITLE
Pattern Error - Fluctuation

### ISSUE THREAD

**Issue by phoenixcon** [mikebryant/ac-nh-turnip-prices#120]
Buy Price: 90
Weekly Prices: 81, 77, 73, 68, 64, 98

The patterns include "Fluctuating" but as far as I can tell, Fluctuating shouldn't have a "Decreasing Phase 1" longer than 3 half days. Since the 81 could be increasing phase 1 (due to it being 90% of the original buy price), that puts decreasing phase 1 at 4 half days: 77, 73, 68, 64. 

Source: https://docs.google.com/document/d/1bSVNpOnH_dKxkAGr718-iqh8s8Z0qQ54L-0mD-lbrXo/edit

Other calculator mis-match: https://ac-turnip.com/ (unfortunately this one doesn't list out the pattern options) 

Other calculators don't match either so I'm trying to see if there is an error in one of the sources (since they are all working from the same reverse engineered data in the first place).

**Comment by phoenixcon** [comment]
Looks like there is a 5 bell fudge factor in the tool's code. That seems to be what's causing the problem.

**Comment by mikebryant** [comment]
Yeah, we've had lots of reports of people's patterns not matching, and the only explanation curently is that the floating point implementation in the switch is different is some ways to javascripts. so we're currently adding in the fudge factor to allow for all of those patterns to match
