### ISSUE TITLE
Provide Total Pattern Odds

### ISSUE THREAD

**Issue by astranberg** [mikebryant/ac-nh-turnip-prices#121]
Currently, the program outputs the odds of each remaining sub-pattern out of the original 72. 

Significantly more useful would be the summed odds for each overarching pattern. That way I know there's a 29% chance of a small spike and 71% chance of fluctuating, instead of several subpatterns.

Or why not both?

**Comment by ChiefMilesEdgeworth** [comment]
This is being worked on in  #72.

**Comment by mikebryant** [comment]
Thanks for raising this as an issue - I agree.

I'm going to close this as a duplicte of #72 - please feel free to follow that issue for progress :)
