### ISSUE TITLE
Profit calculator

### ISSUE THREAD

**Issue by SpectreX950** [mikebryant/ac-nh-turnip-prices#129]
A calculator in which you enter how many bells you spent and how much you will gain

**Comment by theRTC204** [comment]
This feature request is out of scope for the project.

From the README

> This tool is not:
> 
> - **A calculator for how much money you'll make**
> - A way to count your turnips
> - A way to store multiple people's islands
> - Something with a backend

**Comment by SpectreX950** [comment]
Just a suggestion to help improve or develop the page.

**Comment by theRTC204** [comment]
Suggestions are alwaays welcome! Just happens that this one in particular is out of scope for the goals of this project.

**Comment by SpectreX950** [comment]
Thanks Mike! 
Maybe a goal for a future project. I’m more than happy to think of more suggestions/comments as well.
