### ISSUE TITLE
Chance of each pattern

### ISSUE THREAD

**Issue by louh** [mikebryant/ac-nh-turnip-prices#13]
Hi! I love this tool and use it every day with my friends :) It paid off last week when someone with a predicted high hit it (519 bells)!

I've been looking at the reverse engineered code, too, and have an idea I'd like to implement, and I'd be happy to take a stab at a pull request if you're interested. What we know is that each of the four price patterns have a chance of happening depending on the previous week's pattern. (So if you had a decreasing pattern last week, your chance of a large spike this week is 50%). Right now, each of the patterns are shown, but we don't have a sense of what are the odds of each pattern occurring.

I'm thinking of adding a dropdown where you can select which of the four patterns you had the previous week (or "unknown", the default choice). It won't be required, only if you happen to know what it is. The results will then calculate what are the odds of each pattern happening. And when we know some patterns won't happen, the chances will be recalculated based on available patterns. It should give someone much more clarity on what their odds are of hitting a large spike, given their prices and previous week's behavior!

Let me know what you think and if you would like me to help!

**Comment by mikebryant** [comment]
I was looking at this earlier - but I'm totally happy for you to take a stab at this, I love collaboration.

**Comment by mikebryant** [comment]
Here's the WIP I have from earlier today: https://github.com/mikebryant/ac-nh-turnip-prices/tree/random-hacks-towards-probability

**Comment by mikebryant** [comment]
Feel free to take that forward or start afresh :)

**Comment by alexwh** [comment]
I made #16 - seems to work well enough for now. I passed the previous_pattern variable to every function but it might be better to make it global or create a class in the future.

**Comment by louh** [comment]
@alexwh I took my own approach last night, and after reviewing your PR I see we did some similar things and differed in others. Any interest in combining efforts?

**Comment by mikebryant** [comment]
I've now gotten this all merged and integrated - but if there's further changes you think we need, open to more issues or PRs. Thanks for your help!
