### ISSUE TITLE
999 to 0

### ISSUE THREAD

**Issue by hunterxyz** [mikebryant/ac-nh-turnip-prices#134]
It looks like there is still a problem, those are my numbers, it brakes when I insert the 3rd number but the previous chart includes 61 as a possibility.

![image](https://user-images.githubusercontent.com/2712457/79458936-d9bbd400-7ff2-11ea-84f4-041a451598fa.png)

**Comment by mikebryant** [comment]
That's really weird because those numbers work for me...

Just a thought, what happens if you force a refresh, ctrl+F5 etc?

![Screenshot from 2020-04-16 14-22-59](https://user-images.githubusercontent.com/1478103/79461242-ce19de80-7fed-11ea-9430-a58f8412d86c.png)

**Comment by hunterxyz** [comment]
The refresh worked. I was sure I did it before opening this issue.

Sorry for the trouble.
