### ISSUE TITLE
Feature request: Ability to share current prediction

### ISSUE THREAD

**Issue by adamfilinovich** [mikebryant/ac-nh-turnip-prices#137]
It'd be really useful if I could save/share a link with the fields filled in so I can compare the turnip prices of multiple people easily.

**Comment by mikebryant** [comment]
This is already possible - there's a "Copy Permalink" button on the page that will allow you to share the link, and also lets you see how to create your own link, from a spreadsheet etc

**Comment by theRTC204** [comment]
Give this functionality already exists, I'm going to go ahead and close this issue. Feel free to open a new one if you believe I am mistaken! 😃
