### ISSUE TITLE
Estimate probability for current patterns based on last week's pattern

### ISSUE THREAD

**Issue by alexwh** [mikebryant/ac-nh-turnip-prices#14]
It'd be nice if you could optionally input the pattern you knew you had last week, and display and sort the probabilities for the next pattern based on [these lines](https://gist.github.com/Treeki/85be14d297c80c8b3c0a76375743325b#file-turnipprices-cpp-L126-L210).

**Comment by mikebryant** [comment]
I'm actually working on this :)

**Comment by eiddor** [comment]
So this is a thing?  I always assumed (apparently incorrectly) that each week was a new "random" event.

**Comment by mikebryant** [comment]
Nope, the probability changes depending on the previous week's pattern choice

I'm closing this in favour of #13 though - same topic :)

**Comment by alexwh** [comment]
Oops, looks like that was posted at the same time, so I didn't see it, my bad.
