### ISSUE TITLE
Patreon or donations link

### ISSUE THREAD

**Issue by SpectreX950** [mikebryant/ac-nh-turnip-prices#141]
Ability to give donations to the developers of the tool.

**Comment by scizzorz** [comment]
:+1:

**Comment by mikebryant** [comment]
I'm investigating this, but most platforms seem to have manual approval processes, and the worldwide Pandemic seems to be slowing this down :(

**Comment by SpectreX950** [comment]
Oh, I see and understand.

**Comment by mikebryant** [comment]
Welp, my Github sponsors profile is now live! https://github.com/sponsors/mikebryant
