### ISSUE TITLE
Issues on commit af8cbe5 and f67b014

### ISSUE THREAD

**Issue by DICE2O** [mikebryant/ac-nh-turnip-prices#144]
af8cbe5 fix-accurate-prob: 
Encountered performance issue on mobile devices. I noticed a significant delay when entering the price using Safari on iPhone and iPad.

f67b014 permalink-copy-button: 
Copying in this way will pop up the keyboard on mobile devices when click the copy button, I suggest using clipboard.js to copy.

**Comment by theRTC204** [comment]
@DICE2O As those two reported issues are not related at all, please create separate issues so they can be tracked individually.
