### ISSUE TITLE
Calculation Issues

### ISSUE THREAD

**Issue by sylve0n** [mikebryant/ac-nh-turnip-prices#145]
These are real prices that my island has, but my result is always minimum: 999 and maximum: 0 no matter what pattern I put as the previous one. No time traveling has happened.
https://turnipprophet.io?prices=95.52.48.45.41.51.96.175.180....

**Comment by theRTC204** [comment]
I will have to do a deeper dive into the calculations a bit later on, but my initial quick review indicates that the 51 you got on Wed AM is impossible. I will break down the calculations deeper later today.

**Comment by taromsn** [comment]
I just got a similar result and have since this morning: https://turnipprophet.io/?prices=98.87.81.77.72.125.132.202.211, no time travel on my end either. Thanks for putting this tool together!

**Comment by sylve0n** [comment]
> I will have to do a deeper dive into the calculations a bit later on, but my initial quick review indicates that the 51 you got on Wed AM is impossible. I will break down the calculations deeper later today.

It may be impossible, but it happened. So not sure what exactly is going on.

**Comment by theRTC204** [comment]
> I just got a similar result and have since this morning: https://turnipprophet.io/?prices=98.87.81.77.72.125.132.202.211, no time travel on my end either. Thanks for putting this tool together!

@taromsn  is this the first week you've bought Turnips on your island? Your pattern is perfectly possible for a buy price that is between 103-110, but not possible for a buy price of 102 or lower.

**Comment by taromsn** [comment]
Ah, I see, this is the first time I bought turnips on my island, but not the first time I ever bought turnips.  My mistake.

**Comment by joey** [comment]
I have a similar issue with different prices: https://turnipprophet.io?prices=.96.91.87.83.78.73.69.145.171...&first=true

Everything was fine until I entered this morning's price of 171

**Comment by theRTC204** [comment]
Thank you for the example data! I will include it in my on-going investigation of this.

**Comment by seanharding** [comment]
Another example. I'm fairly confident in my data (though I don't have screenshots of the prices showing in-game, so I suppose a mistake somewhere is possible). https://turnipprophet.io?prices=.91.87.83.78.74.71.67.62.57.53..&first=true

**Comment by theRTC204** [comment]
@seanharding you've got the "first time buyer" feature enabled - are you certain this week is the first week you've ever bought on your island? Based on your numbers, that doesn't seem right.

First time buyer locks you into a Fluctuating pattern, but your numbers are very clearly showing a Decreasing pattern. If you disable the first time buyer feature, you'll get predictions.

https://turnipprophet.io?prices=.91.87.83.78.74.71.67.62.57.53..

**Comment by lostfocus** [comment]
Another example here: https://turnipprophet.io?prices=110.88.140.170.240.201.94.42.91.67.49.73.81

I think that would be a fluctuating pattern? Or is the 240 on Tuesday enough for a small spike?

**Comment by peter50216** [comment]
> Another example here: https://turnipprophet.io?prices=110.88.140.170.240.201.94.42.91.67.49.73.81
> 
> I think that would be a fluctuating pattern? Or is the 240 on Tuesday enough for a small spike?

This looks like a large spike pattern (Can be seen from deleting the buy price).
This case is interesting and looks like floating point problem (Since 88/110 is exactly 0.8 which is the minimum possible rate for first large spike price), would investigate this more.

**Comment by lostfocus** [comment]
thanks!

**Comment by peter50216** [comment]
> Another example here: https://turnipprophet.io?prices=110.88.140.170.240.201.94.42.91.67.49.73.81
> 
> I think that would be a fluctuating pattern? Or is the 240 on Tuesday enough for a large spike?

Sorry I remembered the numbers incorrectly... The minimum possible rate for first large spike price is 0.85, not 0.8. So since 88/110 < 0.85, this does not match the pattern, but the rest of the data perfectly match the large spike pattern.

Is the buy price 110 the accurate buy price from your own island on last Sunday (and there's no time travel involved in this week)? The maximum possible buy price from the pattern algorithm would be 103, so this is too far to be a floating point problem iiuc.

**Comment by lostfocus** [comment]
It's not actually mine, I'm just the guy in the friend group with a github account. ;) I've asked again and there has been no time travel but the buy price might have been 101. In that case everything seems to work out fine.

**Comment by seanharding** [comment]
> @seanharding you've got the "first time buyer" feature enabled - are you certain this week is the first week you've ever bought on your island? Based on your numbers, that doesn't seem right.
> 

It’s the first time I have bought in the game at all. However I did buy on another island, which may have screwed it up. If that’s a factor it might be helpful if the UI mentions it, even if it can’t predict in that case.

**Comment by theRTC204** [comment]
> It’s the first time I have bought in the game at all. However I did buy on another island, which may have screwed it up. If that’s a factor it might be helpful if the UI mentions it, even if it can’t predict in that case. 

So you're saying that you didn't buy from your island this week?

If that's the case, then you should not have that feature turned on. For what it's worth, the help text above the buttons _does_ already make the "your island" distinction.

**Comment by jdelgallatin** [comment]
I had this same problem, it started when the last two prices (Fri PM and Sat AM) were the same. When I switched Sat AM price down by one bell, the chart normalized. https://turnipprophet.io?prices=108..84.79.75.71.67.113.134.170.183.183 vs https://turnipprophet.io?prices=108..84.79.75.71.67.113.134.170.183.182.

**Comment by mavdnoise** [comment]
I'm also getting this problem. this is my second time buying turnips, and I missed them one week. It's also my first week tracking with this app. I've only ever bought and sold on my island.
https://turnipprophet.io?prices=105.60.71.143.119.131.136.108.71.62.56.105.105

**Comment by theRTC204** [comment]
I have moved the discussion from @jdelgallatin to issue #182 and the discussion from @mavdnoise to issue #184.
