### ISSUE TITLE
Permalink doesn't work with folders

### ISSUE THREAD

**Issue by Makko-debug** [mikebryant/ac-nh-turnip-prices#148]
Permalink button always gives URL like mydomain123.com?prices=.12...........

Even when you have installed the page on a folder like mydomain123.com/turnips/ where you should get mydomain123.com/turnips/?prices=.12...........

Where should I add the folder info and how? Thanks.

**Comment by mikebryant** [comment]
The site is designed to run on turnipprophet.io. Other use is out of scope I'm afraid. This isn't supposed to be software you install elsewhere, it's a single website.

Thank you for your interest though :)

**Comment by Makko-debug** [comment]
How dumb of me.

**Comment by DevSplash** [comment]
You can modify this file if necessary. 
https://github.com/mikebryant/ac-nh-turnip-prices/blob/204df6d4f5bebf63cbd52112d31fbcf4ac766ec1/js/scripts.js#L308
`  return searchParams.toString() && window.location.origin.concat(window.location.pathname, '?', searchParams.toString());`
