### ISSUE TITLE
Cannot find matching pattern

### ISSUE THREAD

**Issue by theRTC204** [mikebryant/ac-nh-turnip-prices#150]
@trombonekenny I'm splitting your report out to a new issue. This has been moved from #133.

> I'm seeing the same 999 to 0 bug on Firefox for MacOS as of this morning. Was working ok yesterday.
> 
> https://turnipprophet.io?prices=93.88.87.97.75.72.68.64.....
> 
> ![image](https://user-images.githubusercontent.com/10765199/79488439-56dd4e00-7fdf-11ea-9e66-c7842e740252.png)
> Looking at other issues, I wonder if my bug might be data entry rather than something in the code (and maybe coincidental that this morning I had enough data points for it to start graphing and narrowing down the patterns). If I trust my buy price, and sell prices after Tuesday PM I can get the data to graph: https://turnipprophet.io/?prices=93....75.72.68.64.....

**Comment by trombonekenny** [comment]
I can't reproduce this and am OK closing it out as data entry error. Sorry!

**Comment by theRTC204** [comment]
No worries! Thank you for following up!
