### ISSUE TITLE
Performance issue on mobile devices

### ISSUE THREAD

**Issue by DICE2O** [mikebryant/ac-nh-turnip-prices#155]
The commit af8cbe5 has performance issue on mobile devices. I can notice significant delay when entering first few prices using Safari on iPhone and iPad, especially when First-Time Buyer was set to Yes.
No same issue before this commit. May be caused by excessive probability calculations.

**Comment by theRTC204** [comment]
I can confirm this performance degradation exists even on desktop computers. Definitely seems to be related to the significant numbers crunching for the new probabilities.

**Comment by peter50216** [comment]
Some idea:

* Reducing the RATE_MULTIPLIER would make the probability calculation (especially the numerical method part) faster, but with less accurate result.
* Implement some debounce time for update on input.
* Move the heavy calculation to a web worker to not slow down the UI.

**Comment by THeK3nger** [comment]
I do not think it is only related to number crunching. After a small profiling I've detected a huge number of `Recalculate Style` events.

<img width="412" alt="Profiling Image" src="https://user-images.githubusercontent.com/133159/79549992-0675f700-8098-11ea-911e-bbb87c3ec17a.png">

These seems related to the waves animation: if I delete those divs, I get better performances. Moreover, I do not know on mobile, but these events seems to spike every time I move the mouse on the page (probably due the other animations and effect). 

They are expected? I thought so, but now I am not sure. I am not an expert of CSS/SVG animations but [this demo](https://codepen.io/1srq/pen/YOwOmN) does not seem to triggers all those Style Recalculations. 🤔

**Comment by zim2411** [comment]
It's definitely due to the waves SVG animation. Disabling the animation defined in the CSS rule `.parallax>use` drops the CPU and GPU usage to basically nothing on my Macbook, with the rule active it's using 25% GPU and 15-20% CPU on my Core i9 Macbook. Could this be optimized or just disabled? It's so subtle I honestly didn't even notice it until I dove into the inspector to try and figure out where the CPU usage was coming from.

**Comment by mikebryant** [comment]
I'm not against removing the animation. The styling is kinda pretty with the multiple waves though, so I'd like to not remove it entirely. Anyone able to take a stab at turning it into a single static pattern? My css-fu is weak.
