### ISSUE TITLE
disabled cookies suddenly break initial layout until input

### ISSUE THREAD

**Issue by Vankog** [mikebryant/ac-nh-turnip-prices#161]
Since today(-ish) the layout is completely broken with disabled cookies:
![broken layout](https://user-images.githubusercontent.com/3804909/79556121-eeef3c00-80a0-11ea-9a54-54dd7eea092a.png)

Was working fine before.

However, the layout springs to life the moment any input is made.

Chrome 80.0.3987.163 (Official Build) (64-bit)

Hope this helps.

**Comment by peter50216** [comment]
Error in console:
```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

Looks like blocking cookies also blocks reading from localStorage, so we need to fall back to not storing anything if the localStorage is not available (and have some UI hint)?
