### ISSUE TITLE
Show a calculated profit value

### ISSUE THREAD

**Issue by Jargonius** [mikebryant/ac-nh-turnip-prices#176]
I would love it if there was a place to input how many turnips you are planning to sell and then it could show you calculated profit values.  As it is now I have to grab the values and calculate that myself.

**Comment by theRTC204** [comment]
Hey there, thank you for the input! Unfortunately we won't be moving forward with this request, as we've previously deemed making this tool a calculator to be out of scope for the project.

Taken from the README.

> This tool is not:
> - **A calculator for how much money you'll make**
> - **A way to count your turnips**
> - A way to store multiple people's islands
> - Something with a backend
