### ISSUE TITLE
Spanish localization requested

### ISSUE THREAD

**Issue by theRTC204** [mikebryant/ac-nh-turnip-prices#177]
We've had a request for Spanish translation if anyone in the community is able to help out with that!

Continuing from #21

**Comment by theRTC204** [comment]
I know previously @hicor13 and @KeruWolf had offered, if either of you are still interested it would be greatly appreciated!

**Comment by KeruWolf** [comment]
Hi there, @theRTC204 !
I couldn't chech this until now, but yes, I ams till interested!

**Comment by theRTC204** [comment]
No rush! Whenever you get the time, tag this issue in your PR.

**Comment by KeruWolf** [comment]
I already created a PR, I hope I did everything correctly. 
Thank you!

**Comment by mauriciabad** [comment]
I checked the PR and everything except 3 strings look fine. (I'm Spanish)

**Comment by KeruWolf** [comment]
Thank you so much for checking! You're right, I missed some lines. I'll try to translate them tomorrow 👍

**Comment by hicor13** [comment]
Hi! I'm still interested in translating, don't understand much but will try to help!

**Comment by mikebryant** [comment]
The spanish localisation is now live!

So I think this issue is done :)

Thanks for your help :)
