### ISSUE TITLE
Text does not load when running from local filesystem

### ISSUE THREAD

**Issue by medievalanubis** [mikebryant/ac-nh-turnip-prices#178]
None of the text gets loaded when running from the local filesystem.

Looking at the console this seems to be the error

`Access to XMLHttpRequest at 'file:///D:/Download/ac-nh-turnip-prices-master/ac-nh-turnip-prices-master/locales/en.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

**Comment by peter50216** [comment]
The best way to develop/run locally would be running a webserver locally. For example, running `python -m SimpleHTTPServer` in the folder.
Many thing don't work with file:// protocol because of security restrictions by browser, so I don't think we can do anything to solve this.

**Comment by mikebryant** [comment]
I'm actually running `google-chrome --allow-file-access-from-files` to develop locally from the filesystem.

**Comment by theRTC204** [comment]
I've been using `webpack-dev-server` to host the app locally for dev.

It might be worth including a section in the README that describes a couple options for running the site in a lightweight development environment.

**Comment by abrad45** [comment]
`python -m SimpleHTTPServer` and `python3 -m http.server` will also work (depending on your version of python).

**Comment by theRTC204** [comment]
I've switched to using

`npx serve`

It's a very simple zero config web server that only requires you have NodeJS on your machine.
