### ISSUE TITLE
Feature Request: Graph Pattern Analysis

### ISSUE THREAD

**Issue by drewpeisner** [mikebryant/ac-nh-turnip-prices#180]
Would be nice if after a full weeks values are entered there was text underneath the graph telling you what kind of pattern you had (i.e. fluctuating, small spike, large spike, decreasing)

**Comment by mikebryant** [comment]
Shouldn't this be clear from the table - when there's only one pattern listed with 100% chance?

**Comment by drewpeisner** [comment]
You’re totally right, Mike. I’m a complete fucking idiot. That said, I think I just didn’t notice it in the table cause - at least on mobile - it’s pretty small and at the very bottom of the page. Maybe after there’s only one pattern left it could become bolded or the cell could be highlighted? Something to make it more obvious for idiots like me.
