### ISSUE TITLE
Page incorrectly logging prices

### ISSUE THREAD

**Issue by kflekac** [mikebryant/ac-nh-turnip-prices#19]
The newly designed webpage is currently recognising the AM/PM inputs for each day as being for separate days in the prediction outputs.

So Monday PM is logged as Tuesdays price, Tuesday AM is Wednesdays price, etc.
Screenshot attached. Error occurs in chrome for Android.

![Screenshot_20200407-123639_Chrome](https://user-images.githubusercontent.com/16280870/78624305-ac717680-78cc-11ea-8ce2-dc9074250ccb.jpg)

**Comment by davidc604** [comment]
Same for iOS Safari.

**Comment by mikebryant** [comment]
Erf, I can see this on mobile - responsive design related issue I think - it's fine on my laptop. Thanks for reporting!
