### ISSUE TITLE
New pattern?

### ISSUE THREAD

**Issue by wulfomo** [mikebryant/ac-nh-turnip-prices#194]
I was projected to be locked in declining by Thursday night, but then spiked on Friday. My buy price was 107, went down steadily every day to low ~60 on Thurs night, then popped up to ~135 Friday morning and stayed in 130s through Sat. It was my first time buying and didn't have much in the line, so I rode it out even though I was supposed to be guaranteed a declining pattern.

**Comment by theRTC204** [comment]
Please provide all the values for the week; without them we cannot troubleshoot this. You can do this easily by clicking the Copy Permalink button below the input fields.

Also, there are no new patterns in the game.

**Comment by RPigott** [comment]
A first-time buyer always gets the small-spike pattern. You need to indicate that it's your first time buying in the question at the top of the page.
