### ISSUE TITLE
Remove i18next from predictions.js

### ISSUE THREAD

**Issue by h2v4c** [mikebryant/ac-nh-turnip-prices#201]
It would be ideal if predictions.js was once again purely the math behind all of the turnip calculations and not FoS code with libraries to import. When decoupled, the calculations can be used for other branching scripts when this project is abandoned - otherwise the calculations are tied to this library.

**Comment by theRTC204** [comment]
This wouldn't be too difficult to accomplish. We could hoist the `pattern_description` out of the pattern results in `js/predictions.js` and insteaad do that mapping in `js/scripts.js`.

That side effect to that is anyone who's using the this prediction code will no longer have a friendly name as part of the prediction result - they'll need to solve for that on their own.

**Comment by mikebryant** [comment]
> It would be ideal if predictions.js was once again purely the math behind all of the turnip calculations and not FoS code with libraries to import.

@h2v4c I'm sorry, I don't know the acronym FoS, could you expand that for me?

**Comment by theRTC204** [comment]
I took it as the Urban Dictionary top result of "Full of Shit".

**Comment by h2v4c** [comment]
My apologies, FoS="Front of site"
