### ISSUE TITLE
Add definition of a small vs large spike or analysis option

### ISSUE THREAD

**Issue by Generic42** [mikebryant/ac-nh-turnip-prices#202]
Feature Request:
It would be nice to see a mouse over or other definition of a Small Spike or Large Spike, even a note showing the %change or delta for these definitions would be helpful. 

Alternately or in addition to this the ability to perform analysis on the input fields to tell us whether or not we had a small or large spike.

**Comment by theRTC204** [comment]
> It would be nice to see a mouse over or other definition of a Small Spike or Large Spike, even a note showing the %change or delta for these definitions would be helpful.

This aspect of your request is already accounted for in #41.
 
> Alternately or in addition to this the ability to perform analysis on the input fields to tell us whether or not we had a small or large spike.

Could you elaborate on this a little? The app already tells you which pattern you have, once you've provided enough data points for it to be able to determine that. Or do you mean for it to tell you what you had last week?

**Comment by Generic42** [comment]
You've got it covered, both these are duplicate, sorry about that.
