### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Adri1** [mikebryant/ac-nh-turnip-prices#21]
Hello!
It is possible in a near future to provide you a French translation? I would like to share your wonderful tool to some friends or people who are not good in English...

**Comment by promarcel** [comment]
I can help with a german translation if help is needed :)

**Comment by thetruegamer** [comment]
I'd be happy to do the french translation. I haven't done web for ages though, so don't know how you'd want to implement the language switch and such.

**Comment by Adri1** [comment]
I don't now as well, I'm just a noob with a very few notions... I'm doing this request just to submit my own translation, but not the code behind.
But still, if i have to do any suggestion, I'd say it could be nice if the code recognize the laguage use by the navigator with and additional laguage switch in a corner of the page.

**Comment by mikebryant** [comment]
I'm open to translations. I don't want to sink a vast amount of effort into setting up infra though, so I'm doing a bit of research into free translation platforms. If anyone knows of anything good, please let me know :)

**Comment by promarcel** [comment]
@mikebryant There are many tools for manage translation or organize them. 
Unfortunately the most web-based services are paid plans and self-hosted solutions need some setup and infrastructure too.

The only free of charge alternative I know is https://poeditor.com
Alternatively we can just set up the strings inside the Repository here, for example by JSON.

For frontend rendering https://github.com/wikimedia/jquery.i18n can help (just a example, which can easily be integrated).

**Comment by mikebryant** [comment]
I've raised a query with https://weblate.org/en-gb/ - see if we can get the free plan for libre projects :)

**Comment by validvoid** [comment]
How about https://crowdin.com/ and I can help with a Chinese translation

**Comment by NullYing** [comment]
Chinese translation with Wechat Mini Program

![image](https://user-images.githubusercontent.com/10618381/79094162-2dc38000-7d89-11ea-89e7-f498e24892ce.png)

**Comment by mikebryant** [comment]
Can't use crowdin for open source unless the project has been active for 3 months

At least unless I pay for it :p

**Comment by theRTC204** [comment]
Are we against maintaining our own translations? I get that it would be a ton more work, and it would be severly limited, but we could ask the community for translations as new regions start using the tool.

We could create the foundation of the localization by wiring up the language file, then it's just a matter of introducing new languages over time as we can get them.

**Comment by Adri1** [comment]
I'm completely up to translate the whole website in French as soon as I know how we will process. From then, it will take me only around 15 to 30 minutes max to wrap up every entry to translate.
I'm not a programmer, just somebody who wants to give some help, so I'm waiting for your propositions.

**Comment by theRTC204** [comment]
I have an idea in my head for how to handle simple translations, which I could probably take a stab at tomorrow (won't have time tonight unfortunately). In the mean time, if someone else wants to give it a whirl, feel free!

**Comment by hicor13** [comment]
Hi! I´m the guy willing to help translate the page in spanish, I´ll follow this thread if you need translation help!

**Comment by KeruWolf** [comment]
Hey!
I am a professional Spanish translator (working in videogame localization at the moment) and I just came here because I wanted to offer my translations for the page!
I've never used GitHub before, so I don't know how things work around here T^T but I'll try to find out.

**Comment by thetruegamer** [comment]
@theRTC204 Did you had any chance to do it or should I go at it ? Was planning to go really quick and dirty for JSON file with the raw sentences (+ the words with emphasis, like Turnip Prophet), if you have something better go ahead.

**Comment by theRTC204** [comment]
I do have a WIP for incorporating [i18next](https://i18next.com) into the project, but I don't think I'll have time to finish it today, sadly.

**Comment by mikebryant** [comment]
Oh dear @theRTC204 - I took at look at this an hour ago to see if anything was happening and didn't see much, so I've got a WIP going too :p

**Comment by theRTC204** [comment]
Oh that's not problem at all! Your PR gives people a chance to start adding to it. If my stuff hasn't been covered by others by the time I can get back to it, I'll do another PR!

**Comment by theRTC204** [comment]
PR #143 relates to this, but does not close it quite yet. If that gets merged, I'll split this out into different issues requesting translations for languages that have been mentioned here.

**Comment by blaaaakuu** [comment]
Hi guys, I'm able to offer Chinese and Japanese Translation :) and have reserved a .ac (animalCrossing?) domain if you guys are interested. 

Cheers!

**Comment by theRTC204** [comment]
@blaaaakuu translations are welcome!! Check out PRs #143, #151, #153 & #154 for examples of how the language file needs to be structured. 👍

**Comment by theRTC204** [comment]
Looks like all offerred languages have been PR'd other than Spanish, so I split that out into #177 and will close this now.
