### ISSUE TITLE
Not sure which pattern it could be, prophet can't predict properly

### ISSUE THREAD

**Issue by Shentoza** [mikebryant/ac-nh-turnip-prices#212]
I'm not sure if this is the right spot, but I can't find my current pattern, since it's invalid according to the prophet.
Buyprice 94
Monday AM 80
PM 145
Tuesday AM 114

No pattern could be matched. What could be the reason for this?

**Comment by mikebryant** [comment]
It looks like this was the first week in which a resident of your island bought turnips from Daisy on your island.

You'll see that [a prediction appears](https://turnipprophet.io?prices=94.80.145.114.........&first=true) if you change the First-Time Buyer option to Yes

Was that the case?

**Comment by Shentoza** [comment]
Indeed! I didn't know it still counted, if you already participated on other islands. But yeah "First time buyer on your own island" seems to be pretty unmistakable.

**Comment by theRTC204** [comment]
Glad things got sorted out! Going to close this issue now.
