### ISSUE TITLE
Showing 999 to 0 and "Infinity"

### ISSUE THREAD

**Issue by eliosfederico** [mikebryant/ac-nh-turnip-prices#213]
After entering the numbers the Prophet only shows 999 to 0 and "Infinity".

https://turnipprophet.io?prices=101.76.124.120.132......../

**Comment by mikebryant** [comment]
It looks like this was the first week in which a resident of your island bought turnips from Daisy on your island.

You'll see that a prediction appears if you change the `First-Time Buyer` option to `Yes`

Was that the case?

**Comment by eliosfederico** [comment]
Yes you are absolutely right. Stupid from me, but thanks for clearing it up!
