### ISSUE TITLE
Prediction issue from olee

### ISSUE THREAD

**Issue by mikebryant** [mikebryant/ac-nh-turnip-prices#214]
Same here
https://turnipprophet.io/?prices=97.129.111.127.75........&pattern=-2&first=true

_Originally posted by @olee in https://github.com/mikebryant/ac-nh-turnip-prices/issues/203#issuecomment-617094024_

**Comment by mikebryant** [comment]
This is actually a different issue - it looks like you're not actually a first-time buyer. Uncheck that option and you'll see your numbers are valid for a pattern

**Comment by olee** [comment]
Those were actually values for a friend who definitely bought the first time.
However he bought the turnips on a different island than his own and I think he did a bit of time traveling **before** buying for the first time - I'm not sure which of those two might affect the calculation.

**Comment by mikebryant** [comment]
If he only bought the turnips on a different island from his own, then he wasn't a first-time buyer of turnips on his own island. (`Is this your first time buying turnips from Daisy Mae on your island?`)

So looks like just a data-entry error, not an issue with the predictions :)

**Comment by olee** [comment]
Ohh, it might be a good idea to make the text bold like

> Is this your first time buying turnips from Daisy Mae on **your own** island?

One more question: What happens when he will now buy turnips on his own island next week? Will it then still cause the first time behavior?

Also I think this should have been discussed in #203 as I think the same thing probably happened to the guy there.

**Comment by mikebryant** [comment]
> Ohh, it might be a good idea to make the text bold like

Sure, sounds reasonable, thanks for the suggestion :)
> One more question: What happens when he will now buy turnips on his own island next week? Will it then still cause the first time behavior?

Yes, it will

> Also I think this should have been discussed in #203 as I think the same thing probably happened to the guy there.
No, I split this out because the issues are different - as I already said in #203, those numbers are impossible, regardless of whether it's first time or not

**Comment by patricksudol** [comment]
https://turnipprophet.io?prices=.105.108.114.67........&first=true

Having the same issue. I initially checked "First Time Buyer" because it was the first time my character bought turnips from Daisy Mae. Checking no seems to correct the model. The caveat is I am not the primary resident on the island and I am pretty confident that the primary resident has bought turnips in previous weeks. Would that have an effect if my character was indeed a first time buyer?

**Comment by theRTC204** [comment]
> Having the same issue. I initially checked "First Time Buyer" because it was the first time my character bought turnips from Daisy Mae. Checking no seems to correct the model. The caveat is I am not the primary resident on the island and I am pretty confident that the primary resident has bought turnips in previous weeks. Would that have an effect if my character was indeed a first time buyer?

@patricksudol does not appear to be a problem to me - just confusion over the wording. Based on your description, you should _not_ enable First Time Buyer. That feature should only be enabled on the first time that a resident of the island bought Turnips on that island.

**Comment by patricksudol** [comment]
> > Having the same issue. I initially checked "First Time Buyer" because it was the first time my character bought turnips from Daisy Mae. Checking no seems to correct the model. The caveat is I am not the primary resident on the island and I am pretty confident that the primary resident has bought turnips in previous weeks. Would that have an effect if my character was indeed a first time buyer?
> 
> @patricksudol does not appear to be a problem to me - just confusion over the wording. Based on your description, you should _not_ enable First Time Buyer. That feature should only be enabled on the first time that a resident of the island bought Turnips on that island.

In hindsight this makes perfect sense: there won't be two different markets on the same island. It get sets in motion when the first resident buys turnips for the first time. 

But at the time I didn't really think about it when I checked the box. I would probably suggest new wording that makes it clear that the clock starts when anybody on the island buys turnips for the first time, e.g:

Is this **the** first time **someone** is buying turnips from Daisy Mae on your island?

**Comment by theRTC204** [comment]
The wording could definitely be improved, I agree.

**Comment by lanaebk** [comment]
How can I open a pull request for this issue? I cloned locally and created a new branch with the fix, but I can't push (got a 403).

**Comment by theRTC204** [comment]
@lanaebk you need to fork the repository into your own namespace, and then make your branch there. Then, you can push to that repo and create a PR from your fork to this repo.

**Comment by lanaebk** [comment]
Great, will do - thanks!
