### ISSUE TITLE
What a surprise! I see "e" in the site

### ISSUE THREAD

**Issue by sakots** [mikebryant/ac-nh-turnip-prices#216]
Excuse me, I'm not good at English.

Look at this link. [https://turnipprophet.io/?prices=107.96.91.86.81........&pattern=3](https://turnipprophet.io/?prices=107.96.91.86.81........&pattern=3)

"Fluctuating" is "2.39e-7%" ! as 0% ?

**Comment by Casamatechs** [comment]
2.39e-7% is just scientific notation. It means the chances are 0.000000239%, which is such a large number to write it down when there's not much space.

**Comment by mikebryant** [comment]
It's a very small number, using [this notation](https://en.wikipedia.org/wiki/Scientific_notation#E_notation)

Thanks for reminding me - I plan to change that to say something like `<0.01%`
