### ISSUE TITLE
What happens when Nook's Cranny is closed?

### ISSUE THREAD

**Issue by L1N3R1D3R** [mikebryant/ac-nh-turnip-prices#218]
Not really a suggestion for a change, more so a question that I think only people who worked with the turnip price algorithm would be able to answer.

I have a 79% chance of a large spike pattern currently. However, Nook's Cranny is about to be closed tomorrow for an upgrade. Do the prices still behave as they would otherwise but without being able to sell, or do they make an exception in this circumstance? I really don't want to miss out on large turnip prices just because my shop is remodeling, plus it could give inconsistent data for what type of pattern I had this week when calculating next week's chances.

**Comment by theRTC204** [comment]
From what I have seen in the code, there is no indication that there is an exception made for Nook's Cranny being renovated during the week.

The prices for your entire week are known to the game already by the time Daisy shows up on your island Sunday morning. So, if your shop ends up being renovated during the week, you will miss out on the prices of that day.
