### ISSUE TITLE
Week Max uses Sunday's price

### ISSUE THREAD

**Issue by Aakodal** [mikebryant/ac-nh-turnip-prices#22]
I'll try to be as clear as possible.

I noticed that "Week Max" column uses Sunday's buying price when it collects every price to get the highest, as we can see on [this screenshot](https://image.prntscr.com/image/w03EwkONRbu6mHoTrDwvYQ.png) (I just removed all the other patterns with Ctrl+Shift+I). We can see that, on each prediction, I'll never reach 92 or more; however, Week Max returns 92, which is Sunday's price.

**Comment by mikebryant** [comment]
Good spot, thanks!
