### ISSUE TITLE
Guaranteed Minimum is off on table

### ISSUE THREAD

**Issue by NolanMelander** [mikebryant/ac-nh-turnip-prices#220]
Noticed when I was inputting my numbers today that the "Guaranteed Minimum calculation is incorrect on the table. Whereas the Graph is showing the correct value.

We can see in the screenshot that the graph shows the correct value of "44" however, every row shows 99.

![Annotation 2020-04-21 111018](https://user-images.githubusercontent.com/25333185/79893046-b57c4080-83c0-11ea-85c8-b28892d501c4.png)

I am currently on lunch at my work, but when I get out of work tonight I can take a look at the code to determine a fix for this, if others agree it is an issue. Due to lunch i didn't have time to look through issues or forks to see if it is already being reported/worked on.

Link for recreating issue:
https://turnipprophet.io?prices=109.134.99.115.........&pattern=3

**Comment by theRTC204** [comment]
Off the hop, that columnn is supposed to report the highest low range value, and in that regard it's doing exactly what it is supposed to do (you got a 99 on Monday PM).

That being said, I thought this column was changed to report only _future_ values? Either that code didn't end up getting merged, or there is a bug in there somewhere.

Definitely should be investigated.

**Comment by mikebryant** [comment]
Nope, that's correct. It's saying that you are guaranteed to see a minimum price of 99 in the future. All of those ranges for those patterns/days are valid. The point is though that regardless of which pattern you're in, you're guaranteed to see a minimum of 99 in the future

**Comment by mikebryant** [comment]
While Friday PM could indeed be as low as 44 - if that happens a different day would be at 99

**Comment by theRTC204** [comment]
I apparently didn't look close enough at the table and completely missed the low end 99s mid-week.

😬
