### ISSUE TITLE
First-Time Buyer Prediction Issue

### ISSUE THREAD

**Issue by PenguinPride87** [mikebryant/ac-nh-turnip-prices#221]
I'm a first-time turnip buyer, and I was trying to use the calculator to find out my predictions for the week. I have put both prices in each day, both in the calculator and in a Google Sheet. However, the predictions do not come up with my purchase price as a valid option. I have made sure that First-Time Buyer is marked yes, the previous week's pattern is marked I Don't Know, and there is not a price in the Sunday purchase price. After buying for 99 bells/turnip, Monday AM was 96, Monday PM was 92, Tuesday AM was 104, and Tuesday PM was 117. It only shows options with purchase prices from 106-110 bells.

https://turnipprophet.io?prices=.96.92.104.117........&first=true

**Comment by mikebryant** [comment]
This is exactly what it's supposed to do :)

The first time a resident buys turnips on an island, the buy prices is reset, and this new hidden buy price is used for the week's selling prices. That's why we explicitly disable the buy price input, because it's no longer relevant.

**Comment by PenguinPride87** [comment]
So when you buy for the first time, it randomizes the buy price that the weekly prices will be based on?

**Comment by mikebryant** [comment]
Yes, that's correct

**Comment by theRTC204** [comment]
That and it also locks you into Pattern 3 (Small Spike). Both of those things only happen for the first week.

In all future weeks, the buy price you saw in game will be what your weekly sell prices are based on.
