### ISSUE TITLE
I'm seeing different results than my friend is using the same data?

### ISSUE THREAD

**Issue by themagpieswarble** [mikebryant/ac-nh-turnip-prices#222]
Here's my friend's current data:

https://turnipprophet.io/?prices=102.85.80.77

When I open this up, I see he has a 100% chance of getting a Small Spike.. and nothing else. It looks like this:

![image](https://user-images.githubusercontent.com/42039852/79895162-4f40ef00-83bb-11ea-91b6-5df3c637bbcb.png)

Whereas he sees this:

![image](https://user-images.githubusercontent.com/42039852/79895121-3fc1a600-83bb-11ea-867c-04f7ee0a46d9.png)

Is it because it's remembering some previous data he entered from last week possibly that's making his data more reliable?

Thank you!

**Comment by theRTC204** [comment]
Both of you should make sure that you've done a hard refresh (ctrl+f5 / cmd+r) on your browsers, because one of you has out of date code that is cached in your browser.

**Comment by themagpieswarble** [comment]
Ahh! Thank you :)
