### ISSUE TITLE
Animated background

### ISSUE THREAD

**Issue by BrandonGul** [mikebryant/ac-nh-turnip-prices#224]
Would anybody be opposed to a animated background?

**Comment by theRTC204** [comment]
We already have animated clouds in the background, and they are extremely taxing on people's computers; especially mobile devices.

So, my main reservervation with this idea is around performance. We're already looking at potentially removing the animation that exists right now to improve the app performance across lower end devices.

**Comment by BrandonGul** [comment]
Gotcha. I was messing around with animating the main polka dot background. It looks nice, but the idea of performance issues seems like more of an issue than a cool addition
