### ISSUE TITLE
Summary of predictions not showing results when confidence is 100%

### ISSUE THREAD

**Issue by Generic42** [mikebryant/ac-nh-turnip-prices#225]
Example - https://turnipprophet.io?prices=106.94.90.134.186........

There is 100% change for a Large Spike but the aggregate information shows 0% and 0 min, 0 max
![turniprophet](https://user-images.githubusercontent.com/11068526/79898501-98e40680-83c8-11ea-80d2-86a01c316562.jpg)

The aggregate info is a great new feature, thank you!

**Comment by mikebryant** [comment]
That's not a feature... Are you running some sort of userscript?

**Comment by Generic42** [comment]
> That's not a feature... Are you running some sort of userscript?

100% thought I had it disabled and you all had added it, hard reload resolved it, closing
