### ISSUE TITLE
999 to 0 predictions for whole week

### ISSUE THREAD

**Issue by alisonshrub** [mikebryant/ac-nh-turnip-prices#231]
This is not my first time buying turnips, it's my third.

I think last week's pattern was fluctuating but I can't quite remember.

I am getting 999 to 0 predictions for the whole week with these numbers:

https://turnipprophet.io?prices=108.82.90.86.81.78.......

These are definitely the right numbers as I have been messaging my friends each morning and afternoon with the prices. I have never time travelled.

**Comment by theRTC204** [comment]
Thank you for creating a new issue for this!

I want to clarify, you are absolutely certain that no one has done any time traveling on your Switch? Not just you personally, but anyone who might also be playing on the same console as you (the island is tied to your console, not your Nintendo account/profile).

If you are certain, then I will need to do some number crunching on this, but I won't have time to do that tonight I don't think. I can take a peak at this deeply tomorrow evening (unless someone else in the community wants to crunch the numbers before I can!).

**Comment by alisonshrub** [comment]
I am definitely certain no one has done any time travelling. 

However, if it makes a difference, my husband created a profile and started playing on my island Monday last week so did not buy any turnips, and he also did not buy any turnips this week but this _would_ have been his first Sunday with the opportunity to, if that makes sense. But the prophet is still whack when I change first time buyer to 'yes' anyway. He definitely hasn't done any time travelling either way.

I didn't buy any turnips this week either on my island, I bought them at a friend's island for 102... not sure if that makes any difference either!

No worries at all, thanks so much for the work you do!

**Comment by theRTC204** [comment]
> However, if it makes a difference, my husband created a profile and started playing on my island Monday last week so did not buy any turnips, and he also did not buy any turnips this week but this _would_ have been his first Sunday with the opportunity to, if that makes sense.

The "first time" flag is a truly global flag for the entire island (aka entire Switch console), regardless of which resident it was that did the first ever buy. An important note here is it's _residents only_; if you had a visitor from another Switch console, they would not trigger the "first time" flag; only a resident can do that.

The flag can only be set once, and it happens after Turnip buying closes on Sunday but before selling opens on Monday. So if you had purchased Turnips before your husband did, then there would not be a second triggering of that flag when he eventually buys them.

> I didn't buy any turnips this week either on my island, I bought them at a friend's island for 102... not sure if that makes any difference either!

As long as the numbers you've put into the tool are all from the same island, that won't matter. I see you entered a 108 for the Sunday price, so I'm assuming _your_ island was selling for 108, but you chose to buy from another island for 102? If so, you entered the value correctly!

**Comment by alisonshrub** [comment]
Here are my prices for the rest of the week if it helps

https://turnipprophet.io?prices=108.82.90.86.81.78.74.121.159.380.178.151.49

And yep- my island price was 108.

**Comment by mikebryant** [comment]
Looking at the data, my best guess at what's happened here is that there was a typo when storing your data. The numbers you've given aren't possible by the game's code.

If however the Monday AM price was a typo, instead of being 82 it was actually 92 - then this fits to the large spike pattern.

https://turnipprophet.io/?prices=108.82.90.86.81.78.74.121.159.380.178.151.49

I don't think there's anything to fix here, so I'm going to close this issue. I hope the tool works for you in future, and you make lots of Bells :)

**Comment by alisonshrub** [comment]
Okay, if you think so, but that would mean I typed it wrong in 3 places (a message to my friend straight after I checked the price, and this calculator where the prediction works: https://ac-turnip.com/share?f=108-82-90-86-81-78-74-121-159-380-178-151-49
