### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by matt800** [mikebryant/ac-nh-turnip-prices#235]
1) Is it possible to make an App Store app to use on a mobile phone? I know I'd be willing to pay a few £/$/Euros for this convenience.

2) Is it possible to put a dialogue box for 'How many Turnips purchased'? This could then show you later in the page the projected potential total profit at a glance.

Great work & thank you.

**Comment by matt800** [comment]
(sorry if I posted this in the wrong section!)

**Comment by mikebryant** [comment]
> Is it possible to make an App Store app to use on a mobile phone? I know I'd be willing to pay a few £/$/Euros for this convenience.
I have no plans to deal with app stores.

However, this is set up as a Progressive Web App, so you should be able to load up the site on your phone, and install it as an app, no store required :)

> Is it possible to put a dialogue box for 'How many Turnips purchased'? This could then show you later in the page the projected potential total profit at a glance.
This isn't something that I think is in scope for this project - for one thing, the next request will be "I bought turnips at different prices, can I have multiple fields for this" etc.

Thank you for the feedback and comments though :)

**Comment by matt800** [comment]
Hi,
  1) Ah yes, perfect! I'll try this.
  2) Yes, that makes sense.
Thank you for the quick reply.
