### ISSUE TITLE
assignment to undeclared variable prices in predictions.js

### ISSUE THREAD

**Issue by rikimaruv** [mikebryant/ac-nh-turnip-prices#238]
prices = {
        min: 999,
        max: 0,
      }

=>

let prices ...

I've seen same mistake elsewhere also.

**Comment by rikimaruv** [comment]
This fixes it but I think **const** adds confusion here because members are changed later.

**Comment by peter50216** [comment]
In JavaScript, `const` works somewhat different than in other language that it only disallow rebinding of the variable, not modification of the variable value itself, so the word `const` doesn't really means that the variable is a constant as in most other language.

In my opinion, it's still generally preferred to use the more strict `const` whenever possible (also as shown in several style guides [1] [2] [3]), so `const` would be used in this case.

[1]: https://google.github.io/styleguide/jsguide.html#features-use-const-and-let
[2]: https://github.com/airbnb/javascript#references--prefer-const
[3]: https://eslint.org/docs/rules/prefer-const

**Comment by rikimaruv** [comment]
Does not really matter how object changes here.
Probably just my gripe with javascript, coming from languages with more strict rules :D
Does this produce different code in JS? Looks easier to read for me.
let day_min = 999;
let day_max = 0;
...
global_min_max.push({day_min, day_max});

**Comment by theRTC204** [comment]
```js
const prices = {
  min: 0
  max: 999
}
arr.push(prices);
```
vs
```js
let min = 0;
let max = 999;
arr.push({ min, max })
```

These two things are equivalent; were debating code style and syntactical sugar that this point.
