### ISSUE TITLE
How to tell people about new domain name?

### ISSUE THREAD

**Issue by mikebryant** [mikebryant/ac-nh-turnip-prices#24]
https://turnipprophet.io/

**Comment by po8rewq** [comment]
I would:
 - set the GitHub page to a new file (redirect.html or something)
 - this redirect file should just contain the link to the new page (+ text to explain)

If you don't want a new file in the main repo, point the GitHub page to another branch and change the index.html there, but do the same as above.

I think that would be the easiest, and of course, ask people to bookmark the new url :)

Hope that helps

**Comment by mikebryant** [comment]
Well, it's still the same github pages site - so anything I put in the github pages is at the new domain too. (So the old url isn't going anyway, and they both update at the same time. This isn't an urgent thing)

**Comment by po8rewq** [comment]
ah ah makes sense
the other (odd) option would be in JS the check the location and if it's the old one, redirect to the new one? I guess that should work

**Comment by mikebryant** [comment]
Though that also has implications in terms of the local storage not transferring with that redirect, so people would lose their data

Half tempted just to have some javascript, "If old url, show a link to new url"

**Comment by theRTC204** [comment]
Not sure if you did this intentionally, but the old URL is redirecting automatically to the new URL right now.

**Comment by mikebryant** [comment]
Ohhh. That was not intentional. Hmpf. That's actually bad, it'll disrupt any values people had saved. Bah!
Erf, though the damage has likely already been done.

**Comment by theRTC204** [comment]
Unfortunate, but frankly minor. It's only Tuesday so there's a chance people will remember their prices from the week - and if they don't, it's only one week!

**Comment by mikebryant** [comment]
Yeah. ho hum, I guess this issue is done then
