### ISSUE TITLE
Dark mode toggle hover and transparency issue

### ISSUE THREAD

**Issue by BritainIS** [mikebryant/ac-nh-turnip-prices#241]
When you hover over the dark mode button when in light mode, there are two very slightly different colors: #210d26 and #000000. The dots on the light mode background are slightly lighter than the background of the button. Also, the white part of the button that sits on top of the black background that expands into dark mode when the button is pressed is slightly misaligned. I spent some time trying to fix this but I don't know anything about html or css.

**Comment by theRTC204** [comment]
I'm not following, what exactly is the issue? Perhaps providing a screenshot of what you think is wrong would help.

**Comment by BritainIS** [comment]
![button](https://user-images.githubusercontent.com/59326959/80029705-26048980-84b5-11ea-9c0d-9674a8840882.png) 
The dots on the button are a slightly different color that the background of the rest of the button. It's pretty insignificant, but I don't think it's meant to look like that. 

Also:
![Screenshot from 2020-04-22 16-22-42](https://user-images.githubusercontent.com/59326959/80029946-872c5d00-84b5-11ea-882a-1feb00d4ffaa.png)
There is a bit of black on the bottom right edge of the button which makes it look misaligned.

**Comment by theRTC204** [comment]
Ah, some of this appears to be the result of #237 combined with some issues from the [Darkmode.js](https://darkmodejs.learn.uno/) 3rd party library.

**Comment by DevSplash** [comment]
Could you provide your browser version? I can't reproduce it.

**Comment by DevSplash** [comment]
> Ah, some of this appears to be the result of #237 combined with some issues from the [Darkmode.js](https://darkmodejs.learn.uno/) 3rd party library.

It seems unrelated, but I can fix it.

**Comment by theRTC204** [comment]
> It seems unrelated, but I can fix it. 

It's directly related. That PR is where the opacity was introduced, and the opacity is exactly what is causing the button color to change as you scroll the page.

**Comment by DevSplash** [comment]
> > It seems unrelated, but I can fix it.
> 
> It's directly related. That PR is where the opacity was introduced, and the opacity is exactly what is causing the button color to change as you scroll the page.

I tried to remove the opacity, but the problem persists. The button on the [official website](https://darkmodejs.learn.uno/) also have the problem when using a light background.

![0](https://user-images.githubusercontent.com/15691402/80327352-688be480-886e-11ea-8785-d274bfd475c9.png)

**Comment by theRTC204** [comment]
I'm not refering to the black edge that's peaking out. If you read my original message that you quoted, I do say the reported issues are a combination of that PR and some existing issues in the library itself.

The concerns mentioned about the background are the result of the opacity changes.

The black edge poking out is from the library.

**Comment by DevSplash** [comment]
> I'm not refering to the black edge that's peaking out. If you read my original message that you quoted, I do say the reported issues are a combination of that PR and some existing issues in the library itself.
> 
> The concerns mentioned about the background are the result of the opacity changes.
> 
> The black edge poking out is from the library.

Yes, you are right. Adding background-color instead of the opacity might fix it.

**Comment by BritainIS** [comment]
Awesome!
