### ISSUE TITLE
999 minimum, 0 maximum.  (First week and renovation)

### ISSUE THREAD

**Issue by ChronaTrigger** [mikebryant/ac-nh-turnip-prices#248]
As the title says, I had my renovation on tuesday, and it was on track for a small spike until this morning.  This was my first week buying from my own island.  

Possibly the renovation threw everything a bit off, like the first week?  Just my own guess.

**Comment by theRTC204** [comment]
Can you please provide all your numbers for the week? Ideally a permalink from the app!

As far as the renovations go... We don't have any hard data that suggests one way or the other whether Nook's upgrade could cause the market to shuffle. It's not outside the realm of possibility though.

**Comment by anch56** [comment]
I've also run into the same issue. Here is my permalink: https://turnipprophet.io?prices=102.92.87.116.179.316.107.134.....&pattern=3

**Comment by theRTC204** [comment]
@anch56 can you please report that under a new issue? Prediction issues typically need to be investigated individually.

**Comment by ChronaTrigger** [comment]
Unfortunately, I can't find my way back to the version of the page that has the exact prices.  I closed the tabs after it broke and I sold my turnips at a friends.  I did take a screenshot to share with my friends, though, so hopefully that can help in addition to what I remember exactly.

https://cdn.discordapp.com/attachments/246343041399390219/702901883743764501/unknown.png

What I do remember: sunday was 106, monday AM was 80, PM was slightly lower.  Tuesday was the renovation.  Wednesday AM was about 110 (sorry, it's on the screenshot though) PM was 161.  Thursday AM (the one that broke the prophet), 150, PM 52.

**Comment by mikebryant** [comment]
I'm sorry, the code can be quite sensitive to precise numbers (as it's built following the mined information, and we can filter things out based on whether the number was in one small range or another. Without those, we're not going to be able to investigate this further

I hope you still find the tool useful, and you make lots of bells each week. :)
