### ISSUE TITLE
You could please add support to acept get parameters to auto set the form values?

### ISSUE THREAD

**Issue by christianlc00** [mikebryant/ac-nh-turnip-prices#26]
Hi. The idea would be to be able to put a url like this:

`https://turnipprophet.io/index.html?buy=90&sell_2=80`

And then it was automatically put into the buy input and added to the table.

Only these functions would be necessary:

```
function getSearchParameters() {
    var prmstr = window.location.search.substr(1);
    return prmstr != null && prmstr != "" ? transformToAssocArray(prmstr) : {};
}

function transformToAssocArray(prmstr) {
    var params = {};
    var prmarr = prmstr.split("&");
    for (var i = 0; i < prmarr.length; i++) {
        var tmparr = prmarr[i].split("=");
        params[tmparr[0]] = tmparr[1];
    }
    return params;
}
```

With these functions it would only remain to do something similar to this when the page starts:

```
const params = getSearchParameters();
document.getElementById('buy').value = params.buy;
document.getElementById('sell_2').value = params.sell_2;
```

If you could please add it it would be great, if you have any questions don't hesitate to ask me and I will help you.

Thank you very much in advance, greetings!

**Comment by peter50216** [comment]
I did this on my fork: https://github.com/peter50216/ac-nh-turnip-prices
Would send a pull request for this after I resolve the conflicts with the current master branch.

**Comment by christianlc00** [comment]
Perfect, I await that merge, thank you so much!
