### ISSUE TITLE
Prophet broke after friday am price

### ISSUE THREAD

**Issue by miguelsqrl** [mikebryant/ac-nh-turnip-prices#261]
This is my [permalink](https://turnipprophet.io?prices=97.90.87.82.78.74.70.65.125.206.612..)

I am 100% sure of all the inputs.

Hope it helps improve the prophet.

**Comment by theRTC204** [comment]
Those numbers aren't mathematically possible based on the game's calculations. The peak of a Large Spike is a rate of `6.0` and...
```
97 * 6 = 582
```
The only way you could have gotten a 612 is if your buy price was at least 102.

So, one of a few things must be true here.
- Someone using your Switch did some time traveling causing the numbers to recalculate
- The buy price you entered was not from the same island as the sell prices you entered
