### ISSUE TITLE
Question on if you Time Travelled

### ISSUE THREAD

**Issue by theskypirate** [mikebryant/ac-nh-turnip-prices#263]
I know Time Travelling messes things up, I forgot to record the AM price and my game was already open and I stupidly travelled back (I didn't have the turnips anymore, I'd sold them already).

For next week, do I just set it as if it's my first time buying again, since the Time Travelling would have reset it?

**Comment by theRTC204** [comment]
There is no evidence that time traveling will reset the "first time buyer" flag. What it does do is trigger a new calculation of prices, rendering trackers such as this useless for the week.

**Comment by theskypirate** [comment]
Right, so should I mark next week as the price I paid and just select "Don't Know" for what the price was for this week? It was a small spike, but obviously I messed it up.

**Comment by theRTC204** [comment]
That's right. Tomorrow when you buy, reset the page, and leave last week's pattern as I Don't Know.

**Comment by theskypirate** [comment]
Cheers.
