### ISSUE TITLE
Table Overflows off side until a sell price entered.

### ISSUE THREAD

**Issue by Bpendragon** [mikebryant/ac-nh-turnip-prices#269]
(currently) offending pattern: https://turnipprophet.io?prices=90 (note, initial price chosen is 2 digits to give system best chance of not overflowing)
screencap: 
![image](https://user-images.githubusercontent.com/5448822/80285960-6e05f500-86dd-11ea-9bb0-f0adb78f38a9.png)

As soon as any valid price is entered for Monday the overflow disappears: https://turnipprophet.io?prices=100.110........... (note, chose a 3 digit Sunday value value valid 3-digit Mon AM value for for Fluctuating pattern to give worst chance at overflow, works with valid value in any slot whatsoever, just choose Mon AM for simplicity)

Scrrencap: 
![image](https://user-images.githubusercontent.com/5448822/80286014-c76e2400-86dd-11ea-9b63-70d9470f4dab.png)

This occurs on latest: Chrome, Firefox, and Edge, at viewports from ~1400px across (and smaller and the table also gains a vertical scrollbar), all the way up to 2560px across (that is, my 1440p monitor)

**Comment by Bpendragon** [comment]
Further investigation and possible solutions discussed over on my (admittedly hasty) PR:

https://github.com/mikebryant/ac-nh-turnip-prices/pull/271#issuecomment-619451959

**Comment by mikebryant** [comment]
We've actually cut the Sunday column now, which makes the overall size smaller. Is this still an issue for you?

**Comment by Bpendragon** [comment]
> We've actually cut the Sunday column now, which makes the overall size smaller. Is this still an issue for you?

This fixed the issue. As discussed in the linked PR, only needed about 40 px of extra room, and removing that column was more than enough. 

Closing this issue, and will close related PR momentarily.
