### ISSUE TITLE
RNative App?

### ISSUE THREAD

**Issue by shawnpetros** [mikebryant/ac-nh-turnip-prices#279]
I can probably help wrap/migrate this to RNative, login with FB to save stuff locally/share with friends?

**Comment by theRTC204** [comment]
Porting this project over to something like React Native, or any other native mobile product is not likely in scope for this project.

That being said, it is open source, so if you wanted to build and maintain your own fork that became a mobile native app, you're free to do so.

**Comment by mikebryant** [comment]
I'm not interested in rewriting the app to adopt a framework - I don't see the value of that for a project of this size/complexity. 

I'm happy with the way it currently allows me to install it as a Progressive Web App, I don't see the need for native code.

Thank you for your interest, and I hope you make many Bells :)
