### ISSUE TITLE
Turnip prices in github.io page localStorage not transferred to turnipprophet.io

### ISSUE THREAD

**Issue by zetx** [mikebryant/ac-nh-turnip-prices#29]
Per subject, is there a way to retrieve the turnip prices that were saved in localStorage on the github.io subdomain?  Cheers

**Comment by mikebryant** [comment]
This wasn't forseen unfortunately. Wasn't expecting a redirect to appear. I'm sorry about that.

You can view your own local storage in chrome, e.g. https://ui.vision/howto/view-local-storage. It's a list of numbers, starting with two that are both the buy price.

**Comment by zetx** [comment]
I think Firefox only lets you view the local storage of the hostname in question :( 

However, I was able to grab it from the webappsstore.sqlite db file with 

`select * from webappsstore2 where originKey LIKE '%oi.buhtig.tnayrbekim%';` (First 2 are `buy_price, buy_price`)

Hopefully that can help anyone else looking 

Seriously though, thanks for the app, Mike! :)

**Comment by Trevor-Welch** [comment]
Sharing localStorage between two different domains is often disencouraged. But, you can do it by putting an iframe in that has event listeners that allow you to pull data from the frame

**Comment by validvoid** [comment]
Actually there's a way around this issue. To recover your prices just visit https://mikebryant.github.io/ although you would get a 404 page but you can still open the devtools and retrieve the prices stored before in the local storage.
