### ISSUE TITLE
Different results on Desktop vs Mobile

### ISSUE THREAD

**Issue by Skootur** [mikebryant/ac-nh-turnip-prices#292]
I receive completely different outcomes when I use Google Chrome on my desktop and when I use my Chrome app on my Android phone.
Both read out as:
First Time?: No
Last Week: Small Spike
Sunday: 97
MonAM: 89
MonPM: 105

But on Desktop I get a graph with a three day peak of 193, and on mobile I get a one day peak TuesPM of 582

**Comment by theRTC204** [comment]
The only way this could happen is if one of your devices has a cached version of the app, and thus running outdated code.

**Comment by mikebryant** [comment]
@Skootur Can you try a forced refresh on both, to make sure you have the same code, and see if this is still the case?
