### ISSUE TITLE
Readme does not mention the wonderful pun

### ISSUE THREAD

**Issue by booooh** [mikebryant/ac-nh-turnip-prices#297]
Nowhere in the readme, or site documentation do you make clear the wonderful pun of pronouncing Turnip Prophet as "Turn-a-profit". That should be fixed ASAP ;-)

**Comment by nilihanth** [comment]
Some puns are better left unannounced.  It makes for a more enjoyable experience when it hits.

**Comment by mikebryant** [comment]
Thanks for the suggestion, but I don't think I'll be making this explicit anywhere in the site or readme :)

Hope you keep finding the tool useful, and you manage to turn a profit ;)
