### ISSUE TITLE
Getting infinity for prediction

### ISSUE THREAD

**Issue by coreyhaines** [mikebryant/ac-nh-turnip-prices#312]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yesno
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - yesno

**Describe the bug**
My turnip prices were on a downward path, thursday afternoon's made the chart break.

**To Reproduce**
1. Go to https://turnipprophet.io/?prices=.92.87.83.78.74.70.65.60....&first=true

**Permalink to your prices**
https://turnipprophet.io/?prices=.92.87.83.78.74.70.65.60....&first=true

**Expected behavior**
Not totally sure

**Screenshots**
![image](https://user-images.githubusercontent.com/3962/80751570-a64b7000-8aef-11ea-90b6-dfaa6539b26c.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Brave
 - Version 1.7.98

**Comment by evansantos** [comment]
@coreyhaines  the main problem here is because it's your first turnip buy-out so it causes this problem, next time will be fine, if you put no as first time it will show decreasing pattern

**Comment by theRTC204** [comment]
> @coreyhaines the main problem here is because it's your first turnip buy-out so it causes this problem, next time will be fine, if you put no as first time it will show decreasing pattern

This answer is incorrect, please diregard. The first time buyer has nothing to do with why no pattern could be found.

**Comment by theRTC204** [comment]
@coreyhaines in your values, you've indicated that this is the first time you've purchased turnips, but the values for you sell prices do not agree with that. When it truly is your first time buying, you are locked into a Small Spike pattern for that week, but your values are clearly showing you are in a Decreasing pattern.

To be clear, the First Time Buyer should only be enabled if this week is the first week that you or another resident of your island purchased Turnips _on your island_ and that all the values you are entering into this tool are from _your island_.

If no resident has ever purchased Turnips on your island, or you purchased Turnips on another island, you will not enable that feature.

**Comment by coreyhaines** [comment]
> To be clear, the First Time Buyer should only be enabled if this week is the first week that you or another resident of your island purchased Turnips on your island and that all the values you are entering into this tool are from your island.

This is my first time. I didn't buy turnips, so I don't have a purchase price (for Sunday), but I'm tracking my prices, so that I can have a sense of it for next week's "what was last week's trend".

I'm not sure what I should be doing differently. As far as I can tell, I've filled it out truthfully.

**Comment by RoxasShadow** [comment]
I have got the same problem right now, but it's my second week of turnips.

Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
        yes
Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
        yes
Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
        no


https://turnipprophet.io?prices=106.138.78.69.139.127.67.61.51.63...&pattern=3

**Comment by peter50216** [comment]
> > To be clear, the First Time Buyer should only be enabled if this week is the first week that you or another resident of your island purchased Turnips on your island and that all the values you are entering into this tool are from your island.
> 
> This is my first time. I didn't buy turnips, so I don't have a purchase price (for Sunday), but I'm tracking my prices, so that I can have a sense of it for next week's "what was last week's trend".
> 
> I'm not sure what I should be doing differently. As far as I can tell, I've filled it out truthfully.

If you didn't buy turnips, then this is NOT the first week you've bought turnip, so the First-Time Buyer option should be set to no.

Quote from @theRTC204, emphesis mine.
> To be clear, the First Time Buyer should only be enabled if this week is the first week that you or another resident of your island **purchased** Turnips _on your island_ and that all the values you are entering into this tool are from _your island_.

**Comment by theRTC204** [comment]
To add to what Peter said, which is spot on by the way, there is no point in tracking your previous week's to get a "trend" because all of that is thrown away when you buy for the first time.

Two things happen on the first week that a resident buys from your island.

1. The pattern for that week is locked to Small Spike, nullifying any effect the previous week might have on this week.
2. After Daisy leaves on Sunday, and before Nook's opens on Monday, the game recalculates you Turnip prices.

The latter of which makes the buy price you paid irrelevant. Where in a typical week your buy price is directly related to the possible sell prices, this first week is unique, because the game generates a new buy price that is hidden from you; and this hidden buy price is what was used to calculate your sell prices for this week.

**Comment by theRTC204** [comment]
Closing as it's been a few days without reply, and the comments suggest this was an issue with the inputs given to the tool. Feel free to open a new issue if you believe there is still an issue to investigate here.

**Comment by coreyhaines** [comment]
Thanks. Does appear to be a problem with the inputs. I didn't realize that the first purchase resets things. Thanks!
