### ISSUE TITLE
Predictions are calculated twice when radios are toggled

### ISSUE THREAD

**Issue by TarzanInAJar** [mikebryant/ac-nh-turnip-prices#314]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yes
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - no

**Describe the bug**
It appears that changing a radio toggle (First-Time Buyer, Previous Pattern) triggers `updateContent()` twice - once on the `input` event, another on the `change` event.

**To Reproduce**
1. Set a breakpoint on `updateContent()`
1a. Alternatively, have both the radio buttons and the chart in view (without having to scroll)
2. Change either First-Time Buyer or Previous Pattern options
3. If using the debugger, note that the `updateContent()` function is fired twice
3a. Alternatively, if viewing the chart, notice that the chart is rendered twice in quick sequence

**Permalink to your prices**
https://turnipprophet.io?prices=.50.100.150.200........

**Expected behavior**
updateContent() should only be fired once.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Firefox
 - Version: 75.0 64-bit

**Additional context**
It doesn't appear that listening to the `change` event in addition to the `input` event is necessary - radios all seem to trigger just fine on just `input`. I think this can be fixed by simply removing [this line](https://github.com/mikebryant/ac-nh-turnip-prices/blob/f8a223ad533c02267c7ada23062b80a33acffe37/js/translations.js#L66).

**Comment by theRTC204** [comment]
Thanks for the report. Seems the recently added denounce is what revealed the visible double rendering, because one of them is delayed 500ms.
