### ISSUE TITLE
Add a way to mark TT

### ISSUE THREAD

**Issue by bandie528** [mikebryant/ac-nh-turnip-prices#321]
I track my turnip prices both for the predictions and to provide additional data if it's useful.

Time traveling in game changes the algorithm and turnip price track you are on. 

I don't want to get into the ethics of time traveling right now, but, for example, when you want to move all of your rocks into the same general location and you don't want to play with mannequins on your Island for a week, maybe you time travel so that can be done before you go to bed. 

I want there to be a way to mark data I'm inputting as post time travel. I did The Rock thing Thursday night so I only have Friday a.m. Friday afternoon Saturday a.m. Saturday afternoon data, and it looks like I'm on a fluctuating track, which is useful for predicting next week. 

But figuring out a way to take time travel data and make it useful could be good. 

Or at least a way to mark that tt happened and the data changed. I cleared my week and started inputting from Friday. 

Just a thought.

**Comment by mikebryant** [comment]
If you time travel, you need to wipe all of the data and start over - we already have support for this, there's a button to reset the data. Any data from before that is no longer relevant or useful for prediction, so just removing it is the way to go.

I don't see a need for there to be any way to mark this in the app - the UI already supports missing data, and will do the best it can in the absense of fields like Sunday.

**Comment by theRTC204** [comment]
I share @mikebryant's sentiment here; there's no value in tracking data that occurred before time traveling.

If you want to time travel, have at it! Just know that once you've done it, any data from earlier in the week is useless to you now. The "previous pattern" that would matter next week is whatever pattern you had after your last time travel of the week.
