### ISSUE TITLE
Invalid table viewing on Mi9 Lite

### ISSUE THREAD

**Issue by VaultDweller2077** [mikebryant/ac-nh-turnip-prices#322]
Mi9 Lite
Android 10
Google Chrome 81.0.4044.117

After adding a price, I can't see full table of price, only third of them

![Screenshot_2020-05-03-14-47-36-347_com android chrome](https://user-images.githubusercontent.com/15139731/80913444-52d65d80-8d4d-11ea-86e9-a6e78f99e5fd.jpg)

**Comment by akccakcctw** [comment]
same with https://github.com/mikebryant/ac-nh-turnip-prices/issues/274

**Comment by theRTC204** [comment]
This is likely fixed in #276.
