### ISSUE TITLE
Minimum value of infinity, max value of negative infinity

### ISSUE THREAD

**Issue by TomR172** [mikebryant/ac-nh-turnip-prices#330]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yes
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - no

**Describe the bug**
When I enter my values for today, I get a range of 999 to 0 for each day, with a min of infinity and a max of -infinity
**To Reproduce**

1. Go to https://turnipprophet.io
2. Click on "No" "Decreasing
3. Selling value: 92, Monday AM value: 72, PM value: 76

**Permalink to your prices**
https://turnipprophet.io?prices=92.72.76..........&pattern=2

**Expected behavior**
I expect to be able to see an accurate prediction of my prices for the rest of the week

**Screenshots**
![image](https://user-images.githubusercontent.com/1882187/80997769-71009400-8e07-11ea-805e-2451b6dfda7d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.129

**Comment by mikebryant** [comment]
@TomR172 What did the rest of the values for this week end up being?
