### ISSUE TITLE
Allow Dark Mode to be set via Query String

### ISSUE THREAD

**Issue by aelipsi** [mikebryant/ac-nh-turnip-prices#336]
**Is your feature request related to a problem? Please describe.**
When I use an Excel formula to create a link to my turnip prices, I am not able to load the page with dark mode turned on.

**Describe the solution you'd like**
A URL parameter (ex: darkmode or theme=dark) that controls whether the app starts regular or in dark mode. Undecided whether it would be a good idea for the permalink generator to contain the parameter. On one hand if you create it for yourself, you would want to keep it in the same color scheme. On the other hand, if you generate it for someone else, they'd probably want the default experience. 

**Describe alternatives you've considered**
N/A

**Additional context**
At a minimum changes could probably be isolated to scripts.js in getPreviousFromQuery() to load the parameter and initialize() to apply the parameter.

**Comment by brooksbecton** [comment]
Any idea why excel can't load it? 
or is there an example Excel formula I can plug in?

**Comment by theRTC204** [comment]
This is more of a bug than it is an enhancement request.

The application is currently designed to disable all local storage while a query string is present, which was a design decision made at time when the only information stored in local storage was related to the data inputs.

Now that we have user preference settings (such as darkmode) in local storage as well, the approach to how we handle disabling local storage needs to be reconsidered.

**Comment by theRTC204** [comment]
Ok, so after a bit of testing, instead of jumping to a conclusion like my previous comment 😬...

I am not able to replicate your issue. If I load the page, and I set a user preference for the darkmode, then whenever I load the page again from any URL source (spreadsheet, or otherwise) the page loads into my user preferred language & darkmode.

**Comment by aelipsi** [comment]
Oops, I usually use In-Private/Incognito browsing so I didn't notice local storage persisting it! Bit of an obscure use case, so I'll close it. Great work on the utility, by the way!
