### ISSUE TITLE
Error in possible patterns

### ISSUE THREAD

**Issue by wenieboy** [mikebryant/ac-nh-turnip-prices#339]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yes
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - no

**Describe the bug**
The data I have inputted eliminates small spike as a pattern possibility, but I believe it is a potential pattern. 

**To Reproduce**
View my inputted data below

**Permalink to your prices**

https://turnipprophet.io/?prices=103.75.66.60.104........&pattern=3

**Expected performance**
I would expect there to be one remaining small spike pattern as a possibility. 

**Smartphone (please complete the following information):**
 - Device: iphone8
 - OS: current
 - Browser safari
 - Version current

**Comment by chrisgchambers** [comment]
It looks like Small Spike was ruled out on Monday afternoon as 66 is outside the expected range for all patterns but fluctuating. Can you elaborate on why you believe the small spike pattern is still a possibility?

![image](https://user-images.githubusercontent.com/8335772/81115444-f5731580-8ee0-11ea-8b92-e4b73c4300fe.png)

**Comment by wenieboy** [comment]
I see. I didn’t realize that drop was more than was possible for small spike.
