### ISSUE TITLE
Actual Price under Pattern Expected Price, Caused -Inf Max

### ISSUE THREAD

**Issue by pmurr** [mikebryant/ac-nh-turnip-prices#350]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  Yes.
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  Yes.
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  No.

**Describe the bug**
My turnip price in game was below the range that all expected patterns had, this resulted in the Guaranteed Min price becoming Infinite and the Possible Max price becoming -Infinite, as well as all day prices to become "999 to 0".

**To Reproduce**
Reset turnip prophet. Set first time buyer to No. Last week to Small Spike (however have tested with all different last week options and the bug occurs for each).

Sunday Price: 99
Monday AM: 87
Monday PM: 84
Tuesday AM: 80
Tuesday PM: 76
Wednesday AM: 72
Wednesday PM: 52

**Permalink to your prices**
https://turnipprophet.io?prices=99.87.84.80.76.72.52......&pattern=3

**Expected behavior**
The minimum price to be finite and less than the maximum price.

**Screenshots**
Attached patterns before and after Wednesday PM price is added. Am absolutely certain that the Wednesday PM price is the one that was in game.
![UnderflowWedAM](https://user-images.githubusercontent.com/64939843/81247355-3148d080-8ff0-11ea-97e1-e8b1a197b656.PNG)
![UnderflowWedPM](https://user-images.githubusercontent.com/64939843/81247360-3574ee00-8ff0-11ea-9e9b-6c6d37891cf8.PNG)

**Desktop:**
OS: Windows 10
Browser: Firefox
Version: 75

**Comment by lanaebk** [comment]
I experienced this same bug this week and was able to replicate on multiple devices including:

* Mac OS/Firefox
* Mac OS/Chrome
* Android Mobile OS/Chrome

The Sunday price and previous pattern seem to make no difference. The bug occurs once I start to enter the Tuesday PM prices (graph and table were behaving normally until then). I didn't even need to enter/tab to the next price bucket, the first character I entered in Tuesday PM triggers the graph and table to go haywire.

_All Normal_
<img width="963" alt="everything_fine" src="https://user-images.githubusercontent.com/9276095/81373828-b05f0700-90cb-11ea-9288-7271ffe154db.png">

_Once First Char Entered in Tues PM Bucket_
<img width="907" alt="single_tues_char_bug" src="https://user-images.githubusercontent.com/9276095/81373833-b3f28e00-90cb-11ea-8c6e-620230112e0e.png">

[Permalink to full prices entered](https://turnipprophet.io?prices=105.81.83.71.75.71.66.61.57....)

**Comment by theRTC204** [comment]
@lanaebk please submit your report as a separate issue.

**Comment by theRTC204** [comment]
Ok, let's break this down. Based on your values before Wednesday PM, it appears as though you are on track for one of either Decreasing, Large Spike or Small Spike.

**Pattern 1 (Large Spike)** is made up of three phases, `decreasing, high spike, decreasing`. Phase 1 (decreasing) can be anywhere from 1 to 7 price periods, starting with a `rate` multiplier of 0.85 to 0.9, and decreasing by 0.03 to 0.05 each period.

Turnip Prophet then runs a prediction model against the highest and lowest possible rate, once for every possible permutation of periods you could have in this phase. For example, it would run the highest and lowest rate values for 1 period, 2 periods, and so on through the maximum possible of 7 periods in this phase.

Given your values continually decrease up to the point of failure, we can safely assume your game rolled somewhere between 6 to 7 decreasing periods before your spike. For the sake of simplicity, I'll run a model manually for 7 periods.

Starting from a base price of 99 (your buy price), and the highest possible starting rate of 0.9, followed by the smallest decrease of 0.03 for each subsequent period, we get:
```
Sun  Mon  Tue  Wed  Thu  Fri  Sat
 99   90   84   78   72    0    0
      87   81   75    0    0    0
```
And the same number of periods, but with the lowest possible starting rate of 0.85, followed by the largest decrease of 0.05 for each subsequent period, we get:
```
Sun  Mon  Tue  Wed  Thu  Fri  Sat
 99   85   75   65   55    0    0
      80   70   60    0    0    0
```

As you can see in the second table, the lowest possible value you could have for a Wednesday PM is 60, suggesting that your price of 52 is not possible for a Large Spike pattern. Keep in mind, this is based on you having the absolute worst possible rate in every period before it, for which the probability is near zero. The ranges cannot get any wider than this, but they certainly do get tighter as your sell prices are revealed through the week; that means in reality the lowest possible value is likely higher than 60.

Take for example your Wednesday AM price of 72; if we do the math backwards on that value, we can observe that your effective rate is somewhere between `0.71718` and `0.72727‬` in the Wednesday AM period. So, we run the model again with this knowledge, and your possible rate range for Wednesday PM becomes:

Best case:
```
0.72727‬ - 0.03 = 0.69727
99 * 0.69727 = 69.02973
69.02973 + 0.99999 = 70.02972
(int) 70.02972 = 70
```

Worst case:
```
0.71718 - 0.05 = 0.66718
99 * 0.66718 = 66.05082
66.05082 + 0.99999 = 67.05081
(int) 67.05081 = 67
```

At this point we can obvervse with a high degree of confidence that the possible ranges for your Wednesday PM price are somewhere between 67 to 70, making your actual value of 52 impossible.

_Caveat: The above math is only accurate if we assume that your buy price on Sunday was actually 99, and your sell price on Wednesday AM was actually 72. If either of those values were actually different, the results of the math would differ._

**Pattern 2 (Decreasing)** is made up of a single phase, with a starting rate somewhere between 0.85 to 0.9 again, which decreases by 0.03 to 0.05 every period. Knowing that, the exact same math applies as above, which indicates for the given inputs, a value of 52 is impossible for Wednesday PM here as well.

**Pattern 3 (Small Spike)** is made up of three phases, `decreasing, spike, decreasing`, similar to pattern 1, but with a sharper decline and a lower cap in the spike. Phase 1 (decreasing) consists of anywhere from 0 to 7 periods, with a starting rate of 0.4 to 0.9.

Given the upper bounds here are the same as pattern 1, we don't need to run that model again. But we will need to determine the new lower bounds here.

```
Sun  Mon  Tue  Wed  Thu  Fri  Sat
 99   40   30   20   10    0    0
      35   25   15    0    0    0
```

When looking at the results table, at first you might be thinking "Hey, that says the lower bound is 15 for Wednesday PM! 15 is lower than 52!" and you would be correct; however, this model is based on the assumption that you received the lowest possible value in each period, meaning your Monday AM price must have been 40 in order for a 15 to be possible on Wednesday PM. Given your inputs, we know with complete confidence that you did not have the lowest possible value on Monday, you actually had a pretty good value at 87 considering the ceiling is 90.

Using the reversed math I demonstrated earlier, we know with a high degree of confidence that your effective rate on Wednesday AM was between `0.71718` and `0.72727‬`. We also know that each period in the decreasing phase for pattern 3 and pattern 1 use the same math, which means the previously determined worst case value of 67 applies to this pattern as well.

----

All that is to say, given the input values provided throughout the earlier days in the week, a value of 52 is impossible for Wednesay PM.

From this, we can summize that the input values are wrong in some way, which begs a few questions:
1. How confident are you in the values for every day in this week?
2. Are all of the values (buy price, and all sell prices) from the exact same island?

**Comment by pmurr** [comment]
All turnip prices are from the same island. I'm absolutely certain of the Sunday Price and the Wednesday PM price, putting only these into the calculator gives viable patterns.

The others, it is possible that a transcription error occurred! I'm fairly confidant in at least the leading digit of each, since I find a transposition error unlikely. Using the leading digits x 10 (and deleting duplicate 80s i.e. Mon PM and Tues AM) gives a viable fluctuating pattern. My turnip prices today fit into this pattern so it seems possible there was an input error earlier in the week on my end!
