### ISSUE TITLE
Ridiculous odds?

### ISSUE THREAD

**Issue by KLPD123** [mikebryant/ac-nh-turnip-prices#352]
Hello, this is a general question about how the stalk market works rather than this program. For the past three weeks I have had a decreasing pattern. Never once has my turnip price been higher at a time after Monday AM. I’m very baffled as to why this is, or if I’m doing something wrong that is causing the trend to only go down. According to turnip prophet, there’s a 15% chance any week to have a decreasing pattern unless you had it the week before, which makes it only 5%. Wouldn’t that mean the odds of getting it three times in a row 1/375 (15 • 5 • 5)? Am I really that unlucky or is something wrong with my game or the way I’m buying turnips? I buy a ton each week. I don’t time travel either by the way. I understand the probabilities may be slightly off since this is a new program, but this is improbable regardless.

**Comment by theRTC204** [comment]
From the code that has been extracted from the game, there is no indication what so ever that a player's actions can directly effect their Turnip prices.

The only known things that will effect the pricing is:
1. In the first week a resident of your island buys turnips, you are locked to Pattern 3 (Small Spike)
2. Any amount of backwards time traveling will result in your prices being regenerated

Outside of that, there is nothing known that will lock you into a given pattern. Even the time traveling simply causes the calculations to run again, but they run with the exact same probabilities as if it were a normal Sunday calculation.

It seems as though you just have really bad luck... Maybe never buy a lotery ticket?

**Comment by KLPD123** [comment]
Thank you for the reply! My luck sure is unfortunate in that case. I hope my bad luck ends next week, I’ll let you know if it doesn’t!
