### ISSUE TITLE
First Time Buyer option generates way more possibilities

### ISSUE THREAD

**Issue by NeatNit** [mikebryant/ac-nh-turnip-prices#354]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yes
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - no

**Describe the bug**
Enabling First Time Buyer with just a buy price creates 168 possible patterns, all of them Small Spike.
Disabling First Time Buyer with just a buy price creates a total of only 72 possible patterns, of which only 8 are Small Spike.

If I've read the reverse-engineered code and the write-up correctly, there shouldn't be more possibilities for first-time buyers than returning buyers.

**To Reproduce**
1. Observe the total of 168 possibilities at https://turnipprophet.io?prices=100&first=true
2. Observe the total of 72 possibilities at https://turnipprophet.io?prices=100
3. Go "hold on a minute..."

I do believe this is all the relevant information. Just in case: I'm using Brave, but I just checked on Firefox and Chrome and the same thing occurs.

**Comment by mikebryant** [comment]
When you buy for the first time, on the Monday morning the prices get regenerated using another randomised buy price, that's hidden from you, and forced to be small spike.

This means that the actual buy price is unknown, and therefore the predictor tries all possible combinations of buy price & small spike, leading to the number of different predictions.

Does that answer your question? :)

**Comment by NeatNit** [comment]
Yup. Sorry for wasting your time!
