### ISSUE TITLE
Support for GET values

### ISSUE THREAD

**Issue by TheTural** [mikebryant/ac-nh-turnip-prices#362]
I think it would be a useful feature to be able to pass values to the site via GET variables in the URL.

Example: https://turnipprophet.io/?first=false&previous=decreasing&price=90&monAM=80&monPM=85

Or better yet, just as an array passed to a GET variable. [false,decrease,90,80,85,etc]

This is mostly just for my use case, but I could see it being useful for others. I track the prices for several friends of mine in a spreadsheet, and with GET support I could make an automatically-updating link in that spreadsheet that goes to the site with the values pre-populated, rather than having to clear and re-enter them to check the different people's potential prices.

**Comment by theRTC204** [comment]
This functionality already exists; you can see an example implementation by clicking the "Copy permalink" button from the app UI.
