### ISSUE TITLE
Unfilled license.

### ISSUE THREAD

**Issue by alexislours** [mikebryant/ac-nh-turnip-prices#370]
While the project contains an Apache 2.0 license, said file is unfilled which most likely makes it invalid.

`Line 189 - Copyright [yyyy] [name of copyright owner]`

This would means default copyright laws apply, making derivative works, distribution, and reproduction not allowed.

**Comment by slavfox** [comment]
Said file should not be filled. The line you mention explicitly states:

> **To apply the Apache License to your work**, attach the following
    boilerplace notice, with the fields enclosed by brackets "[]"
    replaced with your own identifying information.
[...]
> Copyright [yyyy] [name of copyright owner]
> Licensed under the Apache License, Version 2.0 (the "License");
> you may not use this file except in compliance with the License.
> You may obtain a copy of the License at [...]

Not modifying the license is correct, but the notice dictated by the license is nowhere to be found in the project. The author opted to include the full text of the license in their repo, but did not actually specify that the license does, in fact, apply to this project - having that notice would be ideal.

**Comment by mikebryant** [comment]
I actually disagree, I think it's an accepted practice that a LICENSE file in the root of the repository is a clear implication, without needing to explicitly state that in each and every file. I've added a statement in the COPYRIGHT file though, I hope that helps :)
