### ISSUE TITLE
pattern description question

### ISSUE THREAD

**Issue by Lotti** [mikebryant/ac-nh-turnip-prices#38]
Hello! Me again :D

I was wondering what is meant with `high, decreasing, high, decreasing, high`

Actually i'm in this prediction (very reliable)

<img width="1277" alt="Screen Shot 2020-04-08 at 13 56 15" src="https://user-images.githubusercontent.com/279962/78781603-dac08600-79a0-11ea-8d8e-1aab36f59115.png">

and I'm wondering if "high" means that the price will *always* grow or if it will stay in the "high price" area... 

Let me be more clear with an example:
- It is possible that the price will grow from friday to saturday until a max <=152 
or that 
- the price will remain between 93 and 152 fluctuating on friday and saturday?

An help box with the explaination of the pattern terms could be useful.

Thank you and great domain name :D

**Comment by theRTC204** [comment]
The description `high, decreasing, high, decreasing, high` indicates the pattern that the prices will follow as they adjust throughout the week.

I guess you could say given the information you have available today, both of your bullet points are true? However, as you provide more data, the accuracy of the prediction improves such that the potential values for the rest of the week could decrease.

The algorithm attempts to predict the theoretical maximum value for each given half-day, based on the values from the earlier periods in the week. But, there is still a significant element of random chance in each value. You could have a bad RNG roll which causes you to end up with values on the lower end of each spectrum, which means you could end up with something as low as 97 at the end of the week.

**Comment by theRTC204** [comment]
The pattern also suggests that you should end the week on an upward swing, but it does not mean that your end-of-week value will be higher than your start-of-week value. It just means that the end of the week will be higher than the periods immediately before it.

**Comment by Lotti** [comment]
Thank you for your reply. I have also verified what you said within this week prices
