### ISSUE TITLE
% Chance is incorrect

### ISSUE THREAD

**Issue by Aphoristic** [mikebryant/ac-nh-turnip-prices#384]
Great site, but I have an issue with how the % Chance updates incorrectly.  The game chooses the exact pattern at the start of the week, correct?  This means your updating the % each time it gets clearer what the pattern is can be misleading.  Take this as an example: 
![firefox_2020-05-20_12-00-26](https://user-images.githubusercontent.com/8519290/82482902-29cc0180-9a9d-11ea-92ef-0a231bd36ec4.png)
As you can see, it looks like I'm careening towards a decreasing pattern with these numbers.  But the week started out as:
![firefox_2020-05-20_13-25-35](https://user-images.githubusercontent.com/8519290/82483073-68fa5280-9a9d-11ea-9483-547f62027cd5.png)
With the rest being 45% fluctuating that was quickly ruled out.
**So given the initial odds as they were on Sunday, the % chance of each outcome cannot decrease, only increase as others options are removed.**  So my current odds should look like this:
![firefox_2020-05-20_13-16-53](https://user-images.githubusercontent.com/8519290/82483195-a2cb5900-9a9d-11ea-8e10-13e920d4d0b9.png)

Another way to think of this is as a version of the Monty Hall Problem.  The initial odds of you choosing the right door are 1 in 3, when one gets eliminated, you don't go to 1 in 2 odds, you still have 1 in 3 odds of being a winner where as now the other door has a 2 in 3 chance.  The same principles carry over here, as more patterns are eliminated, the doors close, but the chance of you being in each category (big, small, fluctuating, decreasing) can't decrease, only increase as other categories are entirely eliminated.

**Comment by Lego6245** [comment]
Please read issue #333 for an explanation of how the Monty Hall problem doesn't apply here.
