### ISSUE TITLE
Let user know their inputs are invalid

### ISSUE THREAD

**Issue by John-Kryspin** [mikebryant/ac-nh-turnip-prices#386]
**Is your feature request related to a problem? Please describe.**
Sometimes when entering data you might enter it improperly, which causes the predictor to fail.

**Describe the solution you'd like**
A notification should be shown to the user if they enter data that the predictor cannot find

**Describe alternatives you've considered**

**Additional context**
We can use a simple alert to let the user know that their inputs are incorrect.

**Comment by theRTC204** [comment]
This was implemented in #349
