### ISSUE TITLE
copyright

### ISSUE THREAD

**Issue by xman623** [mikebryant/ac-nh-turnip-prices#389]
Dear developer:
This app uses your webpage and collects advertising revenue.
ios: https://apps.apple.com/tw/app/nooker/id1510011675
android: https://play.google.com/store/apps/details?id=com.nooker.ac

**Comment by Lego6245** [comment]
It really depends on what they're doing. If they're just hosting an embed, then technically there's nothing that can be done about it. If they're rehosting the code, then that's covered under the apache license and is allowed as long as they keep the license visible and state their changes.

**Comment by mikebryant** [comment]
I'm in contact with the author of the above app, thanks for the heads up
