### ISSUE TITLE
Issue with calculate week

### ISSUE THREAD

**Issue by Sblesh** [mikebryant/ac-nh-turnip-prices#40]
I tried to set my week and can't calculate it. If you put 130+ bells in any of the label gives you an error.

I bought turnips in Sunday at 91 bells.
Monday AM were at 120 bells
Monday PM were at 147 bells
Tuesday AM were at 197 bells
Tuesday PM were at 199 bells
Wednesday AM were at 99 bells
Wednesday PM were at 95 bells

**Comment by Aliervo** [comment]
Is it your first week buying turnips?

**Comment by theRTC204** [comment]
We have seen some reports from others that the algorithm is possibly calculating values incorrectly. This still needs to be investigated further and additional examples are greatly appreciated!

There appears to be a few things happening here.

If we assume that this was not your first week buying, then having a sell price of 147 on Monday PM is not possible (based on the predictions model, I mean). So, either this is your first week, or the predictions model is not working.

If this is your first week, then we still have a problem once we get to Wednesday AM, where the predictions model suggests your sell price could not be lower than 146 - your value was 99 though.

In both situations, whether first week or not, there appears to be a calculation issue (this of course is assuming your values are 100% correct, and not possibly typo'd or invalid)

**Comment by rolledback** [comment]
I have seen this as well. 
![image](https://user-images.githubusercontent.com/5074208/78805827-c9fb1a80-7976-11ea-97e8-6bdeb272f1d1.png)
It is the Wednesday PM price which breaks things.
![image](https://user-images.githubusercontent.com/5074208/78805893-dd0dea80-7976-11ea-8f5d-b72b6bca763f.png)

**Comment by theRTC204** [comment]
Thanks for sharing. The more examples people provide, the more information we'll have to hunt down the cause.

**Comment by ElGenerico** [comment]
For me, it is the Tuesday PM price input that broke the calculator.
![chrome_2020-04-08_11-10-36](https://user-images.githubusercontent.com/53555277/78807450-b4dbb700-7989-11ea-844f-5cffaee5db38.png)
![chrome_2020-04-08_11-10-42](https://user-images.githubusercontent.com/53555277/78807453-b5744d80-7989-11ea-9636-9f8e5a8e412f.png)

**Comment by pjbollinger** [comment]
I'm also experiencing this. If you remove the `72` from Wednesday AM it works. I noticed that `71` works, so I'm wondering if there is an off by `1` error. This is *not* the first week of buying turnips (second if it means anything, v1.1.4a)

![Screen Shot 2020-04-08 at 12 35 46 PM](https://user-images.githubusercontent.com/5209474/78809826-7ba94400-7995-11ea-8b31-3a6b8384a4ae.png)

**Comment by rolledback** [comment]
I believe this other web app is using similar methods. They have an issue open right now discussing off by one/precision issues: https://github.com/elxris/Turnip-Calculator/issues/3

May be worth following.

**Comment by theRTC204** [comment]
I've been keeping tabs on that, and comparing results between this app and their app - I have seen several situations where the elxris app produces a prediction, where this one cannot.

**Comment by theRTC204** [comment]
It's worth noting that JavaScript rounds float values differently than C++ does, so there may not be anything that anyone can do to properly address that. Frankly, every language can potentially have slight variations in their floating point math...

**Comment by rolledback** [comment]
Yes, very true. WebAssembly might be a good solution here. Or, running the analysis on a server (but that costs more $$$ 😋) .

**Comment by theRTC204** [comment]
Neither is likely, I don't think. My understanding is the maintainer would like to keep this lightweight and without a back end. Also, Web Assembly would require a complete rewrite of the entire app, so it's essentially a new project.

**Comment by mikebryant** [comment]
Yeah, anything involving a backend is too heavyweight for me

How far out are we anyway.. I'm half wondering whether to just add a bell of fudge factor either way if needed to find a prediction. Is that good enough?

**Comment by theRTC204** [comment]
Tough to say this point. Some of the examples show a variance in the 10s or greater, which does suggest a calculation issue more than a rounding issue.

**Comment by Aliervo** [comment]
Speaking of WebAssembly, someone did make [this](https://github.com/chengluyu/turnip-price). But it would still require a significant rewrite to incorporate.

**Comment by ptrain24** [comment]
Monday PM broke for me.  (Not sure if additional examples are helping at this point... but I thought I would share.

![image](https://user-images.githubusercontent.com/63375269/78837451-b6bd6e80-79b9-11ea-851f-917ceaa0ed0f.png)

**Comment by theRTC204** [comment]
> Monday PM broke for me. (Not sure if additional examples are helping at this point... but I thought I would share.

What were all your values? The example is only beneficial if we can use it to replicate (need your buy price at least)

**Comment by ptrain24** [comment]
Here you go.  Changing the probability of the previous week doesn't affect anything in this case.

![image](https://user-images.githubusercontent.com/63375269/78838141-2718bf80-79bb-11ea-98b3-9a7f55d67072.png)

**Comment by theRTC204** [comment]
> Here you go. Changing the probability of the previous week doesn't affect anything in this case.

Thanks! It's possible this could be a rounding issue. The lower bounds from the prediction for Monday PM is `72` but you got a `71`. Do you happen to know what the rest of your week looked like?

**Comment by ptrain24** [comment]
Yep: 

![image](https://user-images.githubusercontent.com/63375269/78838756-79a6ab80-79bc-11ea-8b76-563b2687feaa.png)

**Comment by theRTC204** [comment]
Thanks again. More than just the Monday PM value appears to be outside the ranges of the prediction. This is helpful.

**Comment by tylermatchett** [comment]
Here are some values I have gotten this week that causes this issue. the Thursday AM value is the kicker here, at 62, which is the real value, it does not work, but at 61 it does.

This one here is not working
![notworking](https://user-images.githubusercontent.com/6600325/78897888-43633d80-7a49-11ea-8bd7-2ab312332797.png)

And this one does after decreasing my thursday am value by 1
![working](https://user-images.githubusercontent.com/6600325/78897909-4eb66900-7a49-11ea-874e-975d3c444d37.png)

**Comment by tylermatchett** [comment]
I just posted one with incorrect screen shots, so here is the correction:
I have gotten this issue today with my Thursday AM value
The value Nook quoted was 62, however put into the field it breaks the predition, correct it to 61 and it works, seems to be similar to the issues above, but here's one more for the dataset.

**Not Working**
![notworking](https://user-images.githubusercontent.com/6600325/78898481-41e64500-7a4a-11ea-832d-fe6843551291.png)

**Working**
![working](https://user-images.githubusercontent.com/6600325/78898550-5e827d00-7a4a-11ea-9b89-7c7feabaa8e9.png)

**Comment by wlrlbam** [comment]
First week, purchased at 89
Mon am 89. Mon pm 130
Tues am 109. Tues pm 142
Wed am 151. Wed pm 156
Thur am 154. Thur pm 82.
It broke and did the all 999 starting wed am

**Comment by bli754** [comment]
![Screenshot_20200409-194416](https://user-images.githubusercontent.com/63436314/78957729-045dd800-7a9b-11ea-9f3e-2f0b909085cc.png)

Inputting the Thurs PM broke the calculator :/

**Comment by Vankog** [comment]
Today the Calc broke 💔 for me, too. (same for https://elxris.github.io/Turnip-Calculator/)
![Screenshot_20200410-102406](https://user-images.githubusercontent.com/3804909/78976340-40824e80-7b16-11ea-9bc9-14ed85ccea5e.png)

**Comment by Serxeid** [comment]
More data if it helps. Predicted range for Friday AM was 91-143, actual price is 172. Tested on this tool, https://github.com/drfuzzyness/google-sheets-stalk-market-calculator v1.3, and https://elxris.github.io/Turnip-Calculator/ getting the same results.

![ss (2020-04-10 at 11 00 35)](https://user-images.githubusercontent.com/63470322/79012211-a244b780-7b1a-11ea-9d32-2150710ba071.png)

**Comment by Fae-ok** [comment]
Tuesday PM broke mine. 

![A5B494B0-7A0E-4BDC-9CF4-C2CB81F58B2E](https://user-images.githubusercontent.com/63624146/79214236-d1965400-7e8d-11ea-9b96-48b6f32acef1.png)

**Comment by Fae-ok** [comment]
Tuesday PM broke mine

![8F5752D8-4043-4D76-B475-BC7DF8D45C09](https://user-images.githubusercontent.com/63624146/79214441-1621ef80-7e8e-11ea-96fd-480611b5ed3e.png)

**Comment by theRTC204** [comment]
> Tuesday PM broke mine
@Fae-ok what was your Tuesday PM value?

**Comment by mjdalton** [comment]
I have what looks like to be the same issue.  It broke with Monday's values but I included a screenshot with the values from today just in case
![image](https://user-images.githubusercontent.com/17053247/79259440-55324f80-7e52-11ea-9737-997337584bfc.png)

**Comment by tylermatchett** [comment]
So with the recent changes in #93 it seems to break with this valid data:
[https://turnipprophet.io/?prices=104.95.91.124.201](https://turnipprophet.io/?prices=104.95.91.124.201)

Buy price 104
mam - 95
mpm - 91
tam - 124
tpm - 201

You need to delete both mpm and tam to get it to show anything, or adjust the buy price up 1
