### ISSUE TITLE
New Leaf?

### ISSUE THREAD

**Issue by hajsjdnksksk** [mikebryant/ac-nh-turnip-prices#400]
l really didn’t want to make an account for this and I honestly can’t believe no one has asked yet: Will this work for New Leaf?

I just wanna know if it’ll work for New Leaf or if it is for NH only. I haven’t been able to afford a switch yet because I just got my job back but my NL turnip prices are ALWAYS bad. 

I’ve tried looking up this same tool but for New Leaf and it does not seem to exist. 

Just wanna know if it’s NH exclusive.

**Comment by theRTC204** [comment]
The formula in this app is based on the game code from NH. We do not have access to the game code from NL, so I cannot say whether it will or will not work, but my assumption would be No.

**Comment by hajsjdnksksk** [comment]
Thank you!

**Comment by Ambika653** [comment]
Who the fuck is this why you send me email

**Comment by nonchip** [comment]
according to https://kurtboyer.com/stalkmarket/#turnips (which is a New Leaf prediction tool):

> Does this work in Animal Crossing New Horizons?
Yes ... well, I've been told it works. I've been notified by many time travellers that the predictions are still spot on. I don't time travel, so I haven't been able to test it thoroughly. 

so if that one is accurate for new horizons, it seems logical that the market didn't change all too much and this one is relatively accurate for new leaf too. i'm currently testing that. (without timetravel, so expect me to report some experience in the next few weeks or so)
