### ISSUE TITLE
First week turnip prices not accepted

### ISSUE THREAD

**Issue by resoldren** [mikebryant/ac-nh-turnip-prices#413]
This week was the first week I could buy turnips.  The tool starts rejecting my numbers starting at Tuesday Morning by filling the whole chart green with a range of 0 to 999 for all time windows.

First Time Buyer: Yes
Previous Pattern: I don't know
Sunday: 110
Monday: 152/143
Tuesday: 127*/88
Wednesday: ?/131
Thursday: 143/68
Friday: 62/58
Saturday: 144/137

If I choose 'No' for first time buyer, it works.

**Comment by conan** [comment]
Same, here's a screenshot 
![image](https://user-images.githubusercontent.com/3037019/89919778-9b76a000-dbf3-11ea-9466-c7f66ebd44c7.png)

**Comment by conan** [comment]
Scratch that, mine updated after a couple more values.  Sorry for the noise!
