### ISSUE TITLE
Faulty Predictions

### ISSUE THREAD

**Issue by sirtofu** [mikebryant/ac-nh-turnip-prices#414]
I use the Travel Guide App to monitor my tasks and turnip prices, and this is how I access the turnip prophet. However, lately when I try to see the predictions it’s completely broken. I tried resetting it but the issue persisted. 
![09F4A95D-D890-4BD4-B9FA-697338ED0B08](https://user-images.githubusercontent.com/67333433/85428590-a9386f00-b53a-11ea-8388-875526ef6806.png)

**Comment by dutchtux3000** [comment]
I also got the same problem.
I used the following input:
First-time buyer: no
Previous pattern: I don't know
**Sunday:** 104
**monday am:** 86
**monday pm:** 81
**tuesday am:** 77
**tuesday pm:** 73
**wednesday am:** 107
**wednesday pm:** 107
**thursday am:** 145
**thursday am:** 154
**friday am:** 155
**friday pm:** 90
saturday fields are empty

If I empty out the field for **friday AM** it will give a correct results.

Hopelfully this will help you debuging.
