### ISSUE TITLE
Guaranteed Minimum Infinity

### ISSUE THREAD

**Issue by Patacha1** [mikebryant/ac-nh-turnip-prices#416]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yes
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - no

**Describe the bug**
It says my guaranteed minimum is infinity.  That can't be right.  I put in my prices Monday 81 am and 129 pm.  It said a small spike.  I put in the prices today 129 am and it said 100% chance of a small spike.  This afternoon the price is 430 and it no longer says small spike it says all patterns and they are all 999 to 0 with a guaranteed minimum of infinity and a potential maximum of infinity.

**To Reproduce**

**Permalink to your prices**
Please click the `Copy Permalink` button and paste it here
https://turnipprophet.io?prices=93.81.129.169.430........&first=true

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
chrome on a windows computer

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aifuenzalida** [comment]
You put First Time Buyer YES, when the first week is forced to small spike.
If you change to no, everything is fine https://turnipprophet.io?prices=93.81.129.169.430........

**Comment by ralts00** [comment]
I have the same problem, it is my first week in the game buying turnips and it returns infinity
[https://turnipprophet.io/?prices=105.138.143.69.........&first=true](https://turnipprophet.io/?prices=105.138.143.69.........&first=true)
