### ISSUE TITLE
Mobile Application for iOS and Android

### ISSUE THREAD

**Issue by jakobsieger** [mikebryant/ac-nh-turnip-prices#424]
What about a version in App Store and GooglePlay Store? Is there anything planned?
I'd be very happy about a release in stores!

Greets from Germany

**Comment by kuroidoruido** [comment]
This app is a PWA, so we do not need to use App Store or Play Store to get / update it. 

To doing it the web app needs to be wrapped in a native app. For an android app it pretty easy (but need some work) but for iOS app a mac is mandatory that can be a blocking point. Publishing an app on App store is not free too as the publisher needs to have an Apple developer account that cost $99/year

**Comment by jakobsieger** [comment]
Okay, I see. I didn't know it is a PWA. It would have been cool seeing it in the stores but I definitely agree that there is no need. Especially when the conditions of a Mac and an Apple Developer account are not given.

Thanks for the information!

**Comment by theRTC204** [comment]
There are no plans to introduce a native mobile app for this project, sorry.
