### ISSUE TITLE
Guaranteed Minimum?

### ISSUE THREAD

**Issue by Aliervo** [mikebryant/ac-nh-turnip-prices#43]
Just noticed that the final two columns are ``Guaranteed Minimum`` and ``Potential Maximum``.  I am assuming both are meant for the highest price of the week, correct?

If that is the case, perhaps we should rename the guaranteed min column to something like "Lowest Potential Maximum" and the current potential max to "Highest Potential Maximum".  Maybe it's just me, but "guaranteed minimum" seems to imply that turnips will not go below that price for the entire week.

**Comment by rrsharpe** [comment]
It appears Guaranteed Minimum is the maximum of the lowest prices. This means you will definitely see at least that price some time during the week and should not sell at any price lower than that. It does seem a bit flawed however as it also includes past prices which are no longer accessible.

**Comment by spfennell** [comment]
Yes, we need a column for future minimums, not ones that have already passed
