### ISSUE TITLE
Wrong preditiction

### ISSUE THREAD

**Issue by myzencorner** [mikebryant/ac-nh-turnip-prices#460]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yes
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - no

**Describe the bug**
Predicted 100% minimum price 99/ max 153 for this Saturday afternoon. The price is 56. The prediction was wrong.

**To Reproduce**
Steps to reproduce 

**Permalink to your prices**
Please click the `Copy Permalink` button and paste it here

**

Predicted 100% minimum price 99/ max 153 for this Saturday afternoon. The price is 56. The prediction was wrong.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - iPhone 7
 - OS: 
 - Browser Safari

**Additional context**

**Comment by rctgamer3** [comment]
No permalink specified, marking issue invalid
