### ISSUE TITLE
decreasing, spike, decreasing pattern: ceiling function should be applied to minimum spike value

### ISSUE THREAD

**Issue by chanko08** [mikebryant/ac-nh-turnip-prices#47]
Based on my own turnip prices, and Treeki's original gist, I think there is a small inaccuracy with the spike in the "decreasing, spike, decreasing" pattern. Here's output from the website for my turnip prices (note the 86 value in both predictions):

![issue](https://user-images.githubusercontent.com/859230/78862074-76cfa900-7a04-11ea-9734-6210f48da1a3.PNG)

According to the site, the min for when the spike starts is 86, but this is inconsistent with the Treeki's original gist. For this pattern, the spike values are calculated like so:

```
sellPrices[work++] = intceil(randfloat(0.9, 1.4) * (float)basePrice);
sellPrices[work++] = intceil(randfloat(0.9, 1.4) * basePrice);
rate = randfloat(1.4, 2.0);
sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
sellPrices[work++] = intceil(rate * basePrice);
sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
```

So for `basePrice=96`, the min for the start of the spike should be `ceil(0.9*96) = 87`. Forgive me, I'm not 100% certain of the relevant part in the code, but it appears to be [here](https://github.com/mikebryant/ac-nh-turnip-prices/blob/master/js/predictions.js#L497) where instead of `Math.floor` it should be `Math.ceil`

**Comment by ZZZZzzzzac** [comment]
i guess this is closed by #93?

**Comment by theRTC204** [comment]
Yup, I think you're right!

**Comment by theRTC204** [comment]
Going to close this issue as it appears to be fixed now. Feel free to open a new issue if you think there's still a problem!
