### ISSUE TITLE
Date slot for Sunday

### ISSUE THREAD

**Issue by GiraldTec** [mikebryant/ac-nh-turnip-prices#472]
I sometimes forget to log in the game to sell my turnips. Most of the time I do it early during the next week by changing the date of my switch. Using TurnipProphet I can see clearly which days are left to check. However, if I leave more time to pass, I do not remember which date it was.

I would like the TurnipProphet website to have a slot where I can write the date of that sunday on which I bought turnips.
This way (as long as I don't close the tab on my browser) I can go back to the date I left the game even if it happened long time ago.

**Comment by mikebryant** [comment]
Hi, thanks for the input, I'm sorry I've been inactive recently. I'm afraid I don't think this fits with what I'm aiming for with this project
