### ISSUE TITLE
Probability may not be accurate

### ISSUE THREAD

**Issue by ZZZZzzzzac** [mikebryant/ac-nh-turnip-prices#48]
current algorithm calculates probability via redistribution probability based on user input price falling into some price intervals and rule out those impossible ones, right? But I think this way may not be accurate. (still a good approximation)

say 100 for buy price and 85 on MonAM and last week is pattern3, it rule out pattern0 and redistribute. Total probabilities are:
```
pattern1 = 0.25*1   /(0.25*1+0.15*7/8+0.15*1)=0.47/7=0.0672each
pattern2 = 0.15*7/8 /(0.25*1+0.15*7/8+0.15*1)=0.28
pattern3 = 0.15*1   /(0.25*1+0.15*7/8+0.15*1)=0.247/7=0.0353 each
```

But for pattern 1 and 2 (they follow same rule on Mon so treat as one), it needs : `rate = 0.85 for rate = randfloat(0.85,0.9)`
and for pattern3, it needs: `rate = 0.85 for rate = randfloat(0.4,0.9)`
clearly the probability for pattern3 to get rate = 0.85 is much smaller(10 times) than pattern 1 and 2

using bayes equation it should be:
```
pattern1 = 0.25*0.01/(0.9-0.85) /( 0.25*0.01/(0.9-0.85)+0.15*0.01/(0.9-0.4)+0.15*0.01/(0.9-0.85))=0.602/7=0.0860 each
pattern2 = 0.15*0.01/(0.9-0.85) /( 0.25*0.01/(0.9-0.85)+0.15*0.01/(0.9-0.4)+0.15*0.01/(0.9-0.85))=0.361
pattern3 = 0.15*0.01/(0.9-0.4)  /( 0.25*0.01/(0.9-0.85)+0.15*0.01/(0.9-0.4)+0.15*0.01/(0.9-0.85))=0.0361/7=0.0051 each
```

or generally 
`P(pattern is k | input price is X) = P( X | k) *P(k) / sum(P( X | k) *P(k)) k from 0 to 3`

key here is `P( X | k)`, under pattern_k find probability of input price X, i think assuming X is uniformly distributed in calculated maxmin interval is a good start, since most of turnip price is generated by `sellPrices[work++] = intceil(randfloat(A, B) * basePrice);`, only for decreasing pattern like 
```
rate = randfloat(0.9, 0.85);
    for (work = 2; work < peakStart; work++)
    {
      sellPrices[work] = intceil(rate * basePrice);
      rate -= 0.03;
      rate -= randfloat(0, 0.02);
    }
```
the price X = A-sum(B_k), A and B are uniform distributed but X is bell shape distributed

**Comment by mikebryant** [comment]
I think you're correct, it's not accurate. But my stats knowledge is pretty weak.

I would love to fix that, but it's going to take me some time to figure out how to code that - this is a great analysis to help with that.

Also very open to anyone else providing a PR to fix this :)

**Comment by ZZZZzzzzac** [comment]
I'm working on the code, but know little about JS so can't help with PR. maybe Python or C++ ? or just pseudo code

**Comment by astranberg** [comment]
Not a great statistician myself, but I agree the odds seem funky.

If last week was pattern 1 (high spike), the odds of each pattern is:

- Pattern 0 (fluctuating) - 50%
- Pattern 1 (high spike) - 5%
- Pattern 2 (decreasing) - 20%
- Pattern 3 (small spike) - 25%

But if we eliminate patterns 1 and 2, it follows that the new odds are:

- Pattern 0 (fluctuating) - 66.67%
- Pattern 3 (small spike) - 33.33%

However, if I put in the calculator large spike, buy_price = 100 and monAM = 105, it gives small spike odds of 7.69%!

I'm not certain how the script is calculating 7.69%, and 2.2% for the 42 possible Pattern 0's (fluctuating).

My pseudocode:

```
base_pattern0_odds = 0.50
base_pattern1_odds = 0.05
base_pattern2_odds = 0.20
base_pattern3_odds = 0.25

remaining_pattern0_patterns = x
remaining_pattern1_patterns = x
remaining_pattern2_patterns = x
remaining_pattern3_patterns = x

odds_denominator = 0
if remaining_pattern0_patterns > 0 then
     odds_denominator += base_pattern0_odds
if remaining_pattern1_patterns > 0 then
     odds_denominator += base_pattern1_odds
if remaining_pattern2_patterns > 0 then
     odds_denominator += base_pattern2_odds
if remaining_pattern3_patterns > 0 then
     odds_denominator += base_pattern3_odds

remaining_total_pattern0_odds = base_pattern0_odds / odds_denominator
remaining_total_pattern1_odds = base_pattern1_odds / odds_denominator
remaining_total_pattern2_odds = base_pattern2_odds / odds_denominator
remaining_total_pattern3_odds = base_pattern3_odds / odds_denominator
```

**Comment by ZZZZzzzzac** [comment]
> I'm not certain how the script is calculating 7.69%, and 2.2% for the 42 possible Pattern 0's (fluctuating).
I think the easiest way to illustrate current algorithm is: 
1. choose last week pattern and using predefined probability
(0.5,0.05,0.2,0.15 for your example)
2. calculate all pattern and their subpattern and uniformly distribute to all subpattern 
(there are 56 initial pattern 0 subpattern so you get 0.5/56=0.00893=0.893%)
3. everytime you input a price, it will rule out some impossible subpattern, and recalculate probability for each subpattern based their pervious probability 
( after you input 105 to MonAM, there will only 42 of 56 pattern0 remain, 0 of 7 pattern1 remain, 0 of 1 pattern2 remain, and **only 1 of 7 pattern3 remain**, so you will have 42*0.893%/(42*0.893%+0*0.714%+0*20%+1*3.12%) / 42 = 0.0219 =2.20% for each pattern0
1*3.12%/(42*0.893%+0*0.714%+0*20%+1*3.12%) / 42 = 0.0767 = 7.67% for each pattern3, )

I think you may confused that **only 1 of 7 pattern3 remain** part, this is subpattern `small spike with MonAM price between 90-140`, not the overall `small spike`, it only has 1/7 of all pattern3 probability

**Comment by ZZZZzzzzac** [comment]
Python code here, give current price, base price, and random bound ABCD to get corresponding probability
```
def get_uniform_prob(price,base,A,B): 
    # sellPrices[work++] = intceil(randfloat(A, B) * basePrice);

    # it is uniform distribution
    if price >= int(np.ceil(A*base)) and price <= int(np.ceil(B*base)):
        return (1/base)/(B-A)
    else:
        return 0

def get_uu_prob(price,base,A,B):
    # rate = randfloat(A, B); sellPrices[work++] = intceil(randfloat(C, rate) * basePrice) - 1;

    # => X->U(A,B), Y->U(C,X), Y-C->U(0,X-A), Y-C->U(0,1)*(X-A), Y-C->U(0,1)*U(C-A,B-A)
    # luckly here A=C, let Z=Y-A/B-A,  Z->U(0,1)*U(0,1), Z is product of two 2 uniform distribution
    # pdf_Z = -log(z) cdf_Z = z-z*log(z)
    rate_max = ((price+1)/base-A)/(B-A)
    rate_min = ((price)/base-A)/(B-A)
    cdf = lambda z: 0 if z<=0 else z-z*np.log(z) if z<=1 else 1
    # def cdf(z):
    #     if z > 0:
    #         if z <=1:
    #             return     
    #         else:
    #             return 1
    #     else:
    #         return 0
    return cdf(rate_max)-cdf(rate_min)

def get_bell_prob(price,base,A,B,C,D,L):   
    # rate -= randfloat(A, B);
    # for (work = 2; work < L; work++)    {
    #   sellPrices[work] = intceil(rate * basePrice);
    #   rate -= randfloat(C, D);    }

    # X = U(A,B), Y_k = U(C,D), Z = X-sum(Y_k), sum(Y_k) follows irwin–hall distribution
    # cdf of z is not easy to get, so here i'm using numerical method
    rate_max = ((price)/base-A)/(B-A)
    rate_min = ((price-1)/base-A)/(B-A)
    price_max = np.ceil((B-C*L)*base)
    price_min = np.ceil((A-D*L)*base)

    pdf_X = np.ones(int((B-A)/0.001))/(B-A)
    pdf_Y = np.ones(int((D-C)/0.001))/(D-C)
    pdf = pdf_X
    for i in np.arange(L):
        pdf = np.convolve(pdf,pdf_Y)
    cdf = np.cumsum(pdf)    
    margin = cdf.size/bins
    idx_start = int(np.ceil((price-price_min)*margin))
    idx_end = int(idx_start+margin)
    # idx_end = int(np.ceil((price+1-price_min)*margin))
    return (cdf[idx_end]-cdf[idx_start])/cdf[-1]
```

**Comment by astranberg** [comment]
I'm not sure what the variables A, B, C, D and L refer to.
I do believe the prediction is inaccurate.
If only **1 out of 7 pattern3 remain,** the overall odds that pattern3 is the correct pattern is unchanged, i.e. still 25%. And that 25% should now be redistributed amongst all remaining pattern3 subpatterns (so 25% / 1 = 25%). Instead, the algorithm would redistribute those odds to all patterns, which is incorrect. You ***cannot* redistribute a patterns odds to the remaining unless all of the subpatterns are eliminated.**

**Comment by peter50216** [comment]
From the code itself I feel that you should redistribute a patterns odds to remaining even if there are some subpatterns left.

> If only **1 out of 7 pattern3 remain,** the overall odds that pattern3 is the correct pattern is unchanged, i.e. still 25%. And that 25% should now be redistributed amongst all remaining pattern3 subpatterns (so 25% / 1 = 25%). Instead, the algorithm would redistribute those odds to all patterns, which is incorrect.

I don't think it's true, the odds of getting pattern3 _condition on your current input_ **would** change.

The python code looks good to be except the part that the range is actually uniform on the randfloat(A, B) part, not on ceil(A*base) and ceil(B*base), so there might be a little inaccuracy from there. The current probability on master is definitely off though.

If no one take this, I can try to implement this tomorrow.

**Comment by ZZZZzzzzac** [comment]
> You cannot redistribute a patterns odds to the remaining unless all of the subpatterns are eliminated.

you confused probability with **_conditional probability_**, everytime you feel confusing, using bayes law:
```
P(pattern is 3| give MonAM price 90~140) = P(90~140 | pattern is 3) * P(pattern 3)/ P(90~140)
                                         = 1/8                      * 25% / (1/8*25% + 42/56*50%)
                                         = 1/13 = 7.69%
```

or even easier, take every subpattern as independent events,  it give same answer

> the range is actually uniform on the randfloat(A, B) part, not on ceil(A*base) and ceil(B*base)

you're right, I'm working on fixing that

**Comment by ZZZZzzzzac** [comment]
tried to convert python function to js one, may have bug
```
function get_uniform_prob(price,base,A,B) {
  // sellPrices[work++] = intceil(randfloat(A, B) * basePrice);

  // it is uniform distribution
  var price_max = intceil(B*base)
  var price_min = intceil(A*base)
  var norm = 0
  if (price > price_min && price < price_max) {
    norm = 1
  }       
  if (price == price_min) {
    n
```orm = price_min - A*base
  }
  if (price == price_max) {
    norm = B*base-price_max+1
  }      
  return norm/base/(B-A)
}

function get_uu_prob(price,base,A,B) {
    // rate = randfloat(A, B); sellPrices[work++] = intceil(randfloat(C, rate) * basePrice) - 1;

    // => X->U(A,B), Y->U(C,X), Y-C->U(0,X-A), Y-C->U(0,1)*(X-A), Y-C->U(0,1)*U(C-A,B-A)
    // luckly here A=C, let Z=Y-A/B-A,  Z->U(0,1)*U(0,1), Z is product of two 2 uniform distribution
    // pdf_Z = -log(z) cdf_Z = z-z*log(z)
    var rate_max = ((price+1)/base-A)/(B-A)
    var rate_min = ((price)/base-A)/(B-A)
    var cdf = (z)=> {     
      if (z > 0) {
        if (z <=1) {
          return z-z*Math.log(z)
        } else {
          return 1
        }
      } else {
        return 0
      }  
    }
    return cdf(rate_max)-cdf(rate_min)
}

function conv(vec1, vec2){
  var disp = 0; // displacement given after each vector multiplication by element of another vector
  var convVec = [];
  // for first multiplication
  for (j = 0; j < vec2.length ; j++){
      convVec.push(vec1[0] * vec2[j]);
  }
  disp = disp + 1;
  for (i = 1; i < vec1.length ; i++){
      for (j = 0; j < vec2.length ; j++){
          if ((disp + j) !== convVec.length){
              convVec[disp + j] = convVec[disp + j] + (vec1[i] * vec2[j])
          }
          else{
              convVec.push(vec1[i] * vec2[j]);
          }
      }
      disp = disp + 1;
  }
  return convVec;
}

function get_bell_prob(price,base,A,B,C,D,L) {
    // # rate = randfloat(A, B);
    // # for (work = 2; work < L; work++)    {
    // #   sellPrices[work] = intceil(rate * basePrice);
    // #   rate -= randfloat(C, D);    }

    // # X = U(A,B), Y_k = U(C,D), Z = X-sum(Y_k), sum(Y_k) follows irwin–hall distribution
    // # cdf of z is not easy to get, so here i'm using numerical method
    var price_max   = intceil((B-C*L)*base)
    var price_min   = Math.max(intceil((A-D*L)*base),0)
    if (price>price_max || price< price_min){return 0}
    var bins        = price_max-price_min+1
    var pdf_X       = Array.from({ length: intceil((B-A)/0.001) }).fill(1/(B-A)); 
    var pdf_Y       = Array.from({ length: intceil((D-C)/0.001) }).fill(1/(D-C));
    var pdf         = pdf_X
    for (i=0; i<L; i++) {
        pdf = conv(pdf,pdf_Y)
    }
    const cumulativeSum = (sum => value => sum += value)(0); //cumsum
    cdf             = pdf.map(cumulativeSum)
    var margin      = cdf.length/bins
    var idx_start   = Math.max(intceil((price-price_min)*margin),0)
    var idx_end     = Math.min(Math.floor(idx_start+margin),cdf.length-1)
    return (cdf[idx_end]-cdf[idx_start])/cdf[cdf.length-1]
}

**Comment by peter50216** [comment]
Realized (as in #103) that the price that would affect the rate range is not only the previous known one, so it might be hard to only use `get_bell_prob` to calculate the correct probability.

I'm currently working on using numerical methods all the way down to do this, would send a PR soon after I complete it.

**Comment by ZZZZzzzzac** [comment]
> I realized (as in #103) that the price other than the previous known one might also affect the rate range, so it might be hard to only use get_bell_prob to calculate the correct probability in some edge case.
I doubt, in bell shape distribute, the rate now(rate[n]) is only dependent on the last rate(rate[n-1]) `rate[n] = rate[n-1] -randfloat(A,B) `, not other history rate. It's true that rate[n-1] is dependent on rate[n-2], but once you input pirce[n-1] and derive rate[n-1], that random event is fixed and not conditional anymore
