### ISSUE TITLE
Cannot show output after Tuesday afternoon dropped

### ISSUE THREAD

**Issue by RedsCorner21** [mikebryant/ac-nh-turnip-prices#483]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes/no
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yes/no
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - yes/no

**Describe the bug**

**To Reproduce**

**Permalink to your prices**
Please click the `Copy Permalink` button and paste it here

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RedsCorner21** [comment]
On iPhone SE, safari browser. Input Tuesday afternoon’s number and received an error. Output was predicted to be higher, but input was lower than expected (actual price in town)

**Comment by RedsCorner21** [comment]
Nevermind. I realized I misread the first question as if it was the first time *I* had bought turnips. Another resident had bought turnips before.

**Comment by rctgamer3** [comment]
Closing issue for now since the bug report template wasn't filled in. Since there are many reports, please reply if you've posted more information so that the problem can be investigated.
