### ISSUE TITLE
Unpredicted high spike

### ISSUE THREAD

**Issue by EmilienCourt** [mikebryant/ac-nh-turnip-prices#49]
Hi,
I have tested your tool with the following pattern, which I just got :
Sell Price : 95
Buy Prices : 79, 76, 74, 69, 95, xx, 529
For the 6th value, it was around 145 but I can not tell more precisely (I sold them on an other island before that).
Even entering all the values, your tool can not predict the 529, nor the large spike. It will only predict a small spike if you do not enter the 6th or 7th value, and won't be able to tell the pattern if you do.
No time travel, and no FirstKabuBuy involved.

Thanks a lot for all your work :)
Regards,

**Comment by mikebryant** [comment]
Thanks for the data! That's definitely pointing to some sort of rounding issue - I will continue to investigate

**Comment by ZZZZzzzzac** [comment]
get similiar rounding/ceiling problem with 100 buy and 90,86,80,78,75,72,67, that 78 return empty and last interval is 74-77

**Comment by EmilienCourt** [comment]
It seems like the first value was 80 and not 79, which lead to a wrong determination of the pattern.

Closing this issue
