### ISSUE TITLE
Turnip predictions

### ISSUE THREAD

**Issue by ladycreativity** [mikebryant/ac-nh-turnip-prices#511]
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yes
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - yes

**Describe the bug**
It thinks I time travelled because I forgot to insert my prices from one day this week so I inserted them when I checked my morning prices the day after. I just remembered the prices from the day before and forgot to put them in

**To Reproduce**

**Permalink to your prices**
Please click the `Copy Permalink` button and paste it here

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rctgamer3** [comment]
Bug report form wasn't filled out, no permalink specified. Issue closed
