### ISSUE TITLE
feat: twice buy_price variable

### ISSUE THREAD

**Issue by wngus606** [mikebryant/ac-nh-turnip-prices#525]
[  const prices = [buy_price, buy_price, ...sell_prices];](https://github.com/mikebryant/ac-nh-turnip-prices/blob/f30e1e751e7395ffb5b577164250a1c7590a20c1/js/scripts.js#L157)

I have a question.
Why are you going in here twice?

**Comment by DigitalDragon64** [comment]
Because the turnip price on Sunday AM and PM are always the same, that is the price at which you are buying

**Comment by theRTC204** [comment]
DigitalDragon64 provided the correct answer. Closing this.
