### ISSUE TITLE
All patterns result

### ISSUE THREAD

**Issue by wlrlbam** [mikebryant/ac-nh-turnip-prices#54]
I put in my totals for sun, Mon, Tues, and then after wed am entered, it showed the result as "all patterns" with 0-999 under every prediction. It is a first week input.

**Comment by theRTC204** [comment]
This sounds like the app was not able to identify a prediction for you. Please post your week's values in this issue: https://github.com/mikebryant/ac-nh-turnip-prices/issues/40

**Comment by mikebryant** [comment]
Closing this, not enough data to work with
