### ISSUE TITLE
Specify that the calculator is for New Horizons

### ISSUE THREAD

**Issue by Absolute-Arthur** [mikebryant/ac-nh-turnip-prices#544]
**Is your feature request related to a problem? Please describe.**
I have tried to use this calculator for City Folk. After 4 days of prices going down, there are no more predictions matching my situation, apparently Wild World/City Folk use a different price system. I only learned that this app was for New Horizons when accessing the Github page and seeing the name.

**Describe the solution you'd like**
Having a few words, anywhere on the page, saying that this is for New Horizons.

**Describe alternatives you've considered**
The words could be at the top, or at the bottom near the credits.

**Additional context**

**Comment by rctgamer3** [comment]
It literally says this in the repo title and readme.
