### ISSUE TITLE
Prediction incorrect

### ISSUE THREAD

**Issue by TaylorTayto** [mikebryant/ac-nh-turnip-prices#556]
I had entered the prices of my days correctly and the turnip prophet had predicted a 100% chance of a fluctuating pattern which was reflected in my prices. I got a 100 on Thursday AM but then got a 203 on Thursday PM which I imagine is a small spike and not a fluctuating pattern. Not terrible but still could have ruined my sell price if the prediction had been under accurate for example

**Comment by rctgamer3** [comment]
Follow the bug report format.
