### ISSUE TITLE
Can we break out the part that does the calculations?

### ISSUE THREAD

**Issue by keanfreeman** [mikebryant/ac-nh-turnip-prices#6]
In another project, we’re using the chunk of code in scripts.js above the jQuery that does the actual predictions (generate_possibilities and everything it depends on). We’re generating a google sheet instead of HTML. It’d be nice if the prediction code was separate from the code that generates the HTML.

I was thinking the best way would be to move the code into another git repository and include it in this one as a sub module. That way your website is independent of the code that generates the predictions (would be nice for our project). Also we could make an npm package potentially. 

Let me know what you think 😊

**Comment by jyh947** [comment]
Hey just a heads up, my friend and I forked from mikebryant's code and already finished the Google Sheets integration.  Check it out here:

https://github.com/drfuzzyness/google-sheets-stalk-market-calculator

Get your own copy of the Google Sheets here:

https://docs.google.com/spreadsheets/d/1EqQIjfD-WeDWVBNqk2I_CXjmZtGhTP7LbqZxCT5EAtM/copy

**Comment by mikebryant** [comment]
I've moved it to a separate file, so you can load it via a standard <script> tag etc :)
