### ISSUE TITLE
My pattern is invalid?

### ISSUE THREAD

**Issue by MsHinchy** [mikebryant/ac-nh-turnip-prices#60]
![image](https://user-images.githubusercontent.com/42685385/79012217-07041000-7b23-11ea-9197-f5be3391d7f4.png)

My turnip price was 108, barely above the range of valid patterns I get for my shop prices this week. I have not bought from Daisy Mae on my own island yet, but my friend did come to buy from her, so maybe that has something to do with it?

**Comment by dstaley** [comment]
I think this is a result of wonky floating point math in JavaScript. From what I've read, the original C++ code uses 32-bit integers, and when they're converted to JavaScript's floating point numbers it can result in off-by-one miscalculations.

**Comment by mikebryant** [comment]
I don't think this is an issue with floating point - the difference is much too big.

108*0.85 is 91.8 - so according to the extracted code for a decreasing pattern - your numbers are impossible, Monday AM should be minimum 92

Therefore I think either a resident of your island must have bought turnips that week.. or while we don't think so, the visitor buying turnips must have affected things..

**Comment by 1215drew** [comment]
I've got another instance of invalid pattern numbers this week:

First Time: No
Last Weeks Pattern: Unknown
Sunday: 92
Monday AM: 95
Monday PM: 92
Tuesday AM: 179
Tuesday PM: 253
