### ISSUE TITLE
Reset executed on "Enter"

### ISSUE THREAD

**Issue by kantenkugel** [mikebryant/ac-nh-turnip-prices#62]
When entering the current price, I accidentally hit enter in an attempt to "submit" the value.

This sadly triggered the reset functionality, as it seems to try and submit the values with the next button (Reset Turnip Prophet)

It would be good to somehow prevent the enter event or to add some confirmation dialog

**Comment by kantenkugel** [comment]
Probably the easiest solution would be to move the button outside of the form, since a form automatically tries to submit via first button available, once enter is hit on one of its inputs

**Comment by theRTC204** [comment]
Oh, this must have been a regression introduced when the new UI was pushed. This was previously fixed before then.
