### ISSUE TITLE
[Feature Proposal] Sort output rows by probability, and keep the "All patterns" row at the top.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [mikebryant/ac-nh-turnip-prices#65]
Reading the output table could be more intuitive if the rows were sorted by their probability, so that the most likely outcome is the first one that the user sees.

It would also be nice keep the "All patterns" row at the top of the table as a summary.

If either of these changes sound good, I'd be happy to make a pull request referencing this issue that implements them.

Here's a side-by-side of the current and proposed behavior:
<img width="1195" alt="current_behavior" src="https://user-images.githubusercontent.com/40036383/79050844-9243db00-7be1-11ea-9a68-311ff2bf0a9f.png">

<img width="1186" alt="proposed_change" src="https://user-images.githubusercontent.com/40036383/79050849-a1c32400-7be1-11ea-89c8-45e0d9020c6e.png">

**Comment by ChiefMilesEdgeworth** [comment]
I've put together a PR for this and I've got it ready to go if this gets the green light.

**Comment by theRTC204** [comment]
Well, @mikebryant already gave the issue a 👍 so I would say post your PR.
