### ISSUE TITLE
Insert Turnip Quantity Field 

### ISSUE THREAD

**Issue by CiaranC1988** [mikebryant/ac-nh-turnip-prices#69]
May be a useful visual representation of how much you stand to make. Obviously the math can be done manually very quickly but people appreciate the visual value done for them.

**Comment by timplunkett** [comment]
Note that if this is added and there's math being done, it will need another field to insert the buy price.
Since the existing field is for your island's price to determine the pattern, and you could have bought cheaper on another island.

**Comment by CiaranC1988** [comment]
Roger that.

Thanks for the reply

**Comment by mikebryant** [comment]
I don't think this is in scope for this project. To do it right, we'd need to be able to keep track of how many turnips bought at potentially different prices.. Given the maths for this is so trivial, I think that anyone who wants this can just do this themselves.

For me the value is very much in the prediction, and the best time to sell. How much profit isn't relevant - I want the best price regardless of how much I bought them for.

Thank you for the idea, but I don't think this is for me.
