### ISSUE TITLE
Website Icon, for fun / whoever likes to have icons for shortcuts

### ISSUE THREAD

**Issue by ErinPeril** [mikebryant/ac-nh-turnip-prices#71]
![turnip](https://user-images.githubusercontent.com/63560705/79078565-c21cdc80-7cce-11ea-9a48-ae0eac1fc85f.png)
Not sure how well that'll be accessible, but it's a 144X144 .png picture of a turnip! (copied after the in-game turnip icon!) with transparency~

Enjoy! ErinPeril (on insta by same name ;3)

ALT LINK: [Turnip.png](https://i.imgur.com/6wqtLUo.png)

**Comment by theRTC204** [comment]
> copied after the in-game turnip icon!
When you say copied, do you mean taken from the game files, or designed to look similar?

**Comment by ErinPeril** [comment]
Designed to look like it- not a game extract.

**Comment by theRTC204** [comment]
@ErinPeril can you get me an export of this that's 512x512 and I'll use it to generate some common favicon sizes for the site! 👍

**Comment by theRTC204** [comment]
Just tossing this link here as a decent reference for modern favicon standards.

https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/

**Comment by mikebryant** [comment]
@ErinPeril Yeah, I like this icon - would love to get it at 512 or source file resolution :)

**Comment by ErinPeril** [comment]
Sorry- been busy! Will post various other sizes (512 specifically) in an hour. Sorry again for the wait!

**Comment by mikebryant** [comment]
No problem, thanks for the update :)

**Comment by ErinPeril** [comment]
[128x128](https://i.imgur.com/Rm7Rrz1.png)
[512X512](https://i.imgur.com/1DGcjlc.png)

**Comment by mikebryant** [comment]
Thank you! I'll look at getting this on the site tomorrow, unless someone beats me to it

**Comment by theRTC204** [comment]
Beat ya! :wink:

**Comment by ErinPeril** [comment]
hahaa, Happy to help out! :D
