### ISSUE TITLE
[Feature Proposal] Overall Percent Chance

### ISSUE THREAD

**Issue by nbernabe09** [mikebryant/ac-nh-turnip-prices#72]
Hello,

I was wondering if this could be an additional feature to continue with the statistic trend.

![image](https://user-images.githubusercontent.com/28968121/79079268-ed013380-7cc2-11ea-8627-3c7576128169.png)

I made a `working sample` for the current version as of 4/12/2020. It loops through the data found in the table and adds all of the percent chances per category.

I use the `Custom JavaScript for Websites 2` extension for Chrome to run outside scripts into a page. If anyone wants to sample this in their own browser, you can use the following JavaScript code:

```js
var trend = {};

function getChances() {
  trend = {
    random: {
      chance: 0,
      count: 0,
      min: 0,
      max: 0
    },
    down: {
      chance: 0,
      count: 0,
      min: 0,
      max: 0
    },
    small: {
      chance: 0,
      count: 0,
      min: 0,
      max: 0
    },
    large: {
      chance: 0,
      count: 0,
      min: 0,
      max: 0
    }
  }
  $('#output tr').each(function(){
    var type = $(this).children('td:nth-child(1)').text();
    var percent = parseFloat($(this).children('td:nth-child(2)').text());
    var low = parseInt($(this).children('td:nth-child(16)').text());
    var high = parseInt($(this).children('td:nth-child(17)').text());
    
    switch (type) {
      case 'Fluctuating':
        type = trend.random;
        break;
      case 'Decreasing':
        type = trend.down;
        break;
      case 'Small spike':
        type = trend.small;
        break;
      case 'Large spike':
        type = trend.large;
        break;
    }
    
    type.chance = percent;
    type.count++;
    type.min = low;
    type.max = high;
  });
  
  var totalCount = trend.large.count + trend.small.count + trend.random.count + trend.down.count;
  var randomChance = isNaN(trend.random.chance) ? `${((trend.random.count / totalCount) * 100).toFixed(0)}%` : `${(trend.random.chance * trend.random.count).toFixed(0)}%`;
  var downChance = isNaN(trend.down.chance) ? `${((trend.down.count / totalCount) * 100).toFixed(0)}%` : `${(trend.down.chance * trend.down.count).toFixed(0)}%`;
  var smallChance = isNaN(trend.small.chance) ? `${((trend.small.count / totalCount) * 100).toFixed(0)}%` : `${(trend.small.chance * trend.small.count).toFixed(0)}%`;
  var largeChance = isNaN(trend.large.chance) ? `${((trend.large.count / totalCount) * 100).toFixed(0)}%` : `${(trend.large.chance * trend.large.count).toFixed(0)}%`;
  
  $('.table-wrapper').before(`<div id="extraStats">
    <style>
      #extraStats, #extraStats>div {
        width: 100%;
        display: flex;
        justify-content: space-around;
      }
      #extraStats>div>div>* {
        text-align: center;
      }
      @media (max-width: 768px) {
        #extraStats {
          flex-direction: column;
        }
      }
    </style>
    <div>
      <div>
        <h2>Fluctuating</h2>
        <h3>Chance: ${randomChance}</h3>
        <h3>Min/Max: ${trend.random.min}~${trend.random.max}</h3>
      </div>
      <div>
        <h2>Decreasing</h2>
        <h3>Chance: ${downChance}</h3>
        <h3>Min/Max: ${trend.down.min}~${trend.down.max}</h3>
      </div>
    </div>
    <div>
      <div>
        <h2>Small Spike</h2>
        <h3>Chance: ${smallChance}</h3>
        <h3>Min/Max: ${trend.small.min}~${trend.small.max}</h3>
      </div>
      <div>
        <h2>Large Spike</h2>
        <h3>Chance: ${largeChance}</h3>
        <h3>Min/Max: ${trend.large.min}~${trend.large.max}</h3>
      </div>
    </div>
  </div>`);
}

getChances();

$('body').on('DOMSubtreeModified', '#output', function(){
  $('#extraStats').remove();
  getChances();
});
```
**Edit**: I have modified the above code to include other added suggestions discussed in this issue.

![image](https://user-images.githubusercontent.com/28968121/79300536-e7127a80-7e9b-11ea-974c-caba4a809677.png)

**Comment by theRTC204** [comment]
I do agree, having used the % chance this week, that I feel an overall pattern chance would be personally more beneficial for me.

**Comment by pj4533** [comment]
+1    

Came here to suggest this feature!

**Comment by theRTC204** [comment]
Just to further this along, my reasoning for the request can be visualized in this screenshot. Based on the screenshot, without doing some couch math, it appears as though I'm most likely to get a decreasing pattern this week.

![image](https://user-images.githubusercontent.com/6956413/79150668-c90b2400-7d8e-11ea-9fcd-93cc8146a018.png)

However, if you add all those up, it's actually most likely that I'll get a High Spike pattern this week. With 45% chance of a high spike, 31.5% chance of decreasing, and 23.5% chance of small spike (rounded values).

**Comment by ColMelvin** [comment]
Indeed, the true probability comes from the 4 different patterns.  The values you see take that probability and divide it by the total number of ways that pattern can present itself.  So the overall percent chance is also easier to read.  In the OP the actual values are (exactly):
* Fluctuating: 45%
* Large Spike: 25%
* Decreasing: 15%
* Small Spike: 15%

I think these numbers are much easier to read, simply because of their round value.

----

One thought I had was to use `rowspan` to combine all the common results so that it might look like this:
![image](https://user-images.githubusercontent.com/2002896/79187879-24670180-7de3-11ea-9fef-ca46dee2bad0.png)

**Comment by nbernabe09** [comment]
I would suggest adding a new table with a summary of all the information in the table, an "***at a glance***" look.

```
Trend          | Large Spike
---------------|-------------
Total % Chance |     50%
---------------|-------------
Potential Gain |   450~600
```

Using this webapp in both desktop and mobile conditions, I was overcome with information overload, having to horizontal scroll through the table information to see everything making the experience a little frustrating.

***Stalk Market Wizard*** uses this method, only supplying the user on when to hold or sell based on the user's information, but does not share its findings on possible outcomes.

As more user input is supplied, the original table becomes more relevant to the user. Using this "***at a glance***" approach could simplify the user's decision on whether to hold or sell without having to parse though multiple rows of possible outcomes.

**Comment by ChiefMilesEdgeworth** [comment]
I recommend attaching the total category chance to each possibility in that category, and then just taking the first of a category and rowspanning it. It will be hard to sort the rows in order of total category chance if you can't compare an individual row to another to check for that.
