### ISSUE TITLE
Small spike 3rd and 5th price ranges incorrect

### ISSUE THREAD

**Issue by doopl** [mikebryant/ac-nh-turnip-prices#8]
```
    sellPrices[work++] = intceil(randfloat(0.9, 1.4) * (float)basePrice);
    sellPrices[work++] = intceil(randfloat(0.9, 1.4) * basePrice);
    rate = randfloat(1.4, 2.0);
    sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
    sellPrices[work++] = intceil(rate * basePrice);
    sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
```

- The min and max prices for the 3rd and 5th periods of a small spike should be 1 lower than the min and max prices for the 4th period.

- Once the 4th period's price is known, the max price for the 5th period should be 1 less than the 4th period's price.

Thanks for the handy tool!

Edit: I just noticed this is already mentioned in a TODO comment :)

**Comment by mikebryant** [comment]
Thanks for raising this as an issue, much easier to keep track of than as a TODO :)
