### ISSUE TITLE
Guaranteed Minimum (All Patterns) -- math error

### ISSUE THREAD

**Issue by lchoward** [mikebryant/ac-nh-turnip-prices#80]
The guaranteed minimum for "All Patterns" (the last row) appears to be taking the maximum of the minimums for the "All Patterns" row. However, it seems to me that the guaranteed minimum should actually be the minimum of the guaranteed minimums for all rows above it.

See below. The guaranteed minimum should be 128 rather than 78.

![image](https://user-images.githubusercontent.com/11452064/79140735-6f066080-7d86-11ea-9eda-6919c051d6bf.png)

**Comment by theRTC204** [comment]
I have seen this in my own results as well. I agree with your assessment, but I haven't had a chance to look into a fix yet.

**Comment by mikebryant** [comment]
This is now fixed :)
