### ISSUE TITLE
Add a popover interaction to the pattern names to visualize patterns

### ISSUE THREAD

**Issue by zethussuen** [mikebryant/ac-nh-turnip-prices#81]
**Use case**
Would be helpful if you've been tracking prices elsewhere to determine what your prior week's trend was.

**Proposed mockup**
![image](https://user-images.githubusercontent.com/754158/79142010-db825f00-7d88-11ea-85b7-8895eba9f9e9.png)

**Comment by theRTC204** [comment]
It's an interesting idea, but would likely be very difficult to implement as the periods in each "increase" or "decrease" are random based on chance.

**Comment by zethussuen** [comment]
The intent here was just to show an increase/decrease against the prior period.

My prices last week were something like:
Mon AM: ???
Mon PM: ???
Tue AM: ???
Tue PM: 126
Wed AM: 91
Wed PM: 110
Thu AM: 56
Thu PM: 53
Fri AM: 43
Fri PM: 108
Sat AM: ???
Sat PM: ???

Which I plugged in to determine it was a fluctuating pattern. Could have been easier if I could've just read it as up/down arrows. 

Or am I mis-interpreting your issue that there could be N number of consecutive down or up periods that are RNG?

**Comment by theRTC204** [comment]
> Or am I mis-interpreting your issue that there could be N number of consecutive down or up periods that are RNG?

Yes, this. The pattern is just a pattern; it is only able to predict _how_ the prices will change, but not _when_ they will change. Because of that, visualizing the pattern in 12 arrows could give the false impression that the highs and lows will happen on those specific periods.
