### ISSUE TITLE
Impossible pattern?

### ISSUE THREAD

**Issue by rssteffey** [mikebryant/ac-nh-turnip-prices#82]
I purchased my turnips yesterday for 104 apiece.  This morning (Monday AM) they were 97, and now (Monday PM) they are 92.

I am 100% positive these are the correct prices, but the app has no patterns that allow for 92 right now if I purchased at 104 yesterday.  Is this a floating point case or have I screwed up using it?

(Understood if it may be hard to solve from this minimal case, but it may help as a data point for another issue.  This is also my third week in the stalk market, so I don't think anything special applies)

**Comment by theRTC204** [comment]
Seems like the same off-by-one rounding error that has been reported in several other issues already. There are several patterns available if you change your Monday PM price to 93 Bells.

**Comment by mikebryant** [comment]
Working through the cases...

0/fluctuating:
decreasing phase max is ceil(0.8*104) == 84, therefore the 97 and 92 would both have to be high phase.
high phase min is ceil(0.9*104) == 94, so that rules out the 92

1/high spike
first value would need to be 94 or less

2/decreasing
First value 94 or less again

3/small spike
first value 94 or less if decreasing
But this can be the peak, so
first value is in range of 94 to 146
But then second value needs to be in the same range, and it's not

**Comment by mikebryant** [comment]
@rssteffey And to confirm, this is definitely the buy price on your own island, not the price you bought the turnips for elsewhere?

**Comment by rssteffey** [comment]
Correct.  All three prices were local to my island (I did visit a friend and buy an additional few stacks of turnips for <100, but I didn't think that affected my local prices)

They are 88 now (Tuesday morning)

**Comment by jpblanton** [comment]
I'm having a similar issue. Bought at 107 on Sunday, prices went 115 -> 91 -> 157 as of Tuesday morning. If I remove the Sunday price it shows patterns, but the max predicted Sunday price in those patterns is only 102

**Comment by mikebryant** [comment]
@rssteffey This should be fixed now

@jpblanton What're your prices like today?

**Comment by beastboy92** [comment]
I also have a similiar issue. Since yesterday I have a Nook's cranny and started to monitor my turnip prices. When I put in my data (first time buyer: Yes, Tue AM: 105, Tue PM: 113, Wed AM:120 and Wed PM: 81) I don't get any patterns. Can this be because I only started getting prices yesterday?

**Comment by jpblanton** [comment]
@mikebryant 167 Tuesday PM, 133 today. Which was in line with what the system put out when I left the starting price blank

**Comment by mikebryant** [comment]
@beastboy92 Can you try again? You might have been hit by a brief blip that was fixed in #113 - I see a pattern for you right now when I try

**Comment by mikebryant** [comment]
@jpblanton Just to check, because you didn't say - That buy price is on your own island? And it's not the first week someone who lives on your island has bought from daisy on your island?

Because your data matches perfectly with a lower buy price, which is what happens if you're a first time buyer

**Comment by jpblanton** [comment]
It's the first time I've purchased them; the third Sunday overall. And yes, all my island

**Comment by mikebryant** [comment]
@jpblanton Then I don't think there's a problem - as it says on the site, if it's the first time you're buying them on your own island you need to check the first time buyer option, which disables the buy input. (because it makes a hidden buy price instead and uses that to compute)

**Comment by mikebryant** [comment]
@jpblanton This is your prediction: https://turnipprophet.io/?prices=.115.91.157.167.133&first=true
The hidden buy price was somewhere between 90 and 99.

**Comment by jpblanton** [comment]
Yes, sorry, I misunderstood that as looking for the first time I'd seen
her. Apologies

**Comment by mikebryant** [comment]
No problem. Hope you find the site useful in future! :)
