### ISSUE TITLE
Spanish translation!

### ISSUE THREAD

**Issue by hicor13** [mikebryant/ac-nh-turnip-prices#85]
I'm in charge of an ACNH discord in Spanish and would love to help edit a Spanish version of the calculator, don't know much about HTML5 or coding in general, but could pass you a doc with full translations! Im awaiting any confirmation if my help is needed!

**Comment by VHSCODE** [comment]
This is a good idea but as far as i know, all the text that the calculator uses is hardcoded, this could be fixed by adding multiple language support.

**Comment by theRTC204** [comment]
There's definitely interest in supporting translations, but no decision has been made on the best way to go about it. There's more discussion about multi-language support going on in issue https://github.com/mikebryant/ac-nh-turnip-prices/issues/21.

**Comment by theRTC204** [comment]
Forgot we had this issue and I made a new one #177, so I'll close this as a duplicate.
