### ISSUE TITLE
I can't seem to get any prediction.

### ISSUE THREAD

**Issue by peachy-keen** [mikebryant/ac-nh-turnip-prices#92]
![2020-4-14_7-59-4](https://user-images.githubusercontent.com/63657313/79240821-1b981f00-7e27-11ea-8dc3-cc811288ffb3.PNG)
Am I doing something wrong? My friend couldn't get it to work either. I also tried putting random numbers in to see if it would give me anything else but this is all it predicts.

**Comment by mikebryant** [comment]
Have you done any time travelling at all?

Random numbers won't do much - it only predicts valid patterns from the extracted game code.

The numbers you've put in are impossible - numbers above 220 can only come from the large spike,  and the day immediately preceeding that can *only* be between 1.4 and 2.0 times the buy price - but yours says 77 which is too low.

Extracted game code is here: https://gist.github.com/Treeki/85be14d297c80c8b3c0a76375743325b

**Comment by peachy-keen** [comment]
![2020-04-14_14-01-10](https://user-images.githubusercontent.com/63657313/79241783-5ea6c200-7e28-11ea-9a44-8ffeb2c89f3d.png)

The data is from my friend, I can ask her some questions.

Here's her response "I had a small spike yesterday (104), and as the buying price of my turnips was the highest (110), it means that my big spike, that should have been between Tuesday and Thursday, would have been at max 650 bells. and I got lucky and got REAL CLOSE to the highest high spike.

**Comment by mikebryant** [comment]
Not sure we can do much with this unfortunately. It doesn't fit the algorithm we have at all

**Comment by peachy-keen** [comment]
Alright sorry!

**Comment by peachy-keen** [comment]
I got it! My friend is in a group where they share data on turnips and she put in the wrong number. The number for Tuesday am should be 158. It got it now. Sorry about that! :)

**Comment by mikebryant** [comment]
Ah, yes, that works then, cool. No problem, glad you're finding the tool useful :)
