### ISSUE TITLE
Future App?

### ISSUE THREAD

**Issue by jamesedg222** [mikebryant/ac-nh-turnip-prices#94]
I absolutely love this website and i know its still really early but id love to have this as some type of smartphone app
I'm not sure how hard it is to make an app but it would be really neat if you could log your turnip prices to help calculate the weeks prices, kind of like a built in spreadsheet or something. Anyways great tool

**Comment by theRTC204** [comment]
As of this morning, the website can be installed as a PWA on Android phones - can't help you if you're on iOS though!

In terms of a proper native smartphone app, that's outside the scope of the project. Given it's open source, someone could build one based on the calculations in this project though.

**Comment by mikebryant** [comment]
Yeah, I'm afraid a native app and/or logging previous weeks prices are out of scope for this project. We do have the PWA thing for android and ios (though I understand ios isn't quite as nice for this), and you can also link to the site to prefill values from other tools, spreadsheets etc.

I'm glad you find the website useful though!
