### ISSUE TITLE
All Patterns Min/Max Incorrect

### ISSUE THREAD

**Issue by bktruong** [mikebryant/ac-nh-turnip-prices#98]
The min/max row at the bottom that displays the max range of prices is kind of taking the wrong data. Below is what I see. The all patterns has a different value for the min/max when it should be the same for all 5 rows. 

The app is great! Great job on the interface and rollout! This is just a small bug that doesn't really affect anything, but would be interesting to bring up to you.

![Annotation 2020-04-14 192648](https://user-images.githubusercontent.com/63691152/79292835-f76c2a80-7e86-11ea-8996-f645e301e9f1.png)

**Comment by theRTC204** [comment]
This is an interesting one indeed...

Column by column, the all patterns takes the "lowest low" and "highest high" and creates a summary range for that price period. Then, for the GMin it takes the _highest_ low, and the GMax takes the highest high.

The result of that is a weird situation where the GMin value appears to be incorrect, when it _technically_ isn't incorrect at all.

In any case, it's not a very useful data point, so it should be revisited for sure.
