### ISSUE TITLE
Can I use the calculations used in this for an app that I am working on?

### ISSUE THREAD

**Issue by zhuoweiz** [mikebryant/ac-nh-turnip-prices#99]
So I developed a web app that helps you log previous turnip prices on your island. [AC Turnip Price Logger](https://turnipmaster.app/)
<img width="354" alt="Screen Shot 2020-04-14 at 6 29 22 PM" src="https://user-images.githubusercontent.com/24562073/79295192-f211de80-7e8c-11ea-9e57-99e1ad1afc01.png">

It would be super nice for the users if they could have the forecast result automatically calculated when the data are recorded on the same site.
I will give big credits to this project and the contributors. Can I use this forecast feature on my web app?

**Comment by mikebryant** [comment]
This project is open source, so yes.

You can either use the source (in which case you need to comply with the license and provide attribution), or we also have a feature where you can link to the site and automatically fill in the data.

e.g. For the data above you could send them to this link: https://turnipprophet.io/?prices=108.95.90.86.81&first=yes&pattern=small-spike (pattern and first are optional)

**Comment by zhuoweiz** [comment]
> This project is open source, so yes.
> 
> You can either use the source (in which case you need to comply with the license and provide attribution), or we also have a feature where you can link to the site and automatically fill in the data.
> 
> e.g. For the data above you could send them to this link: https://turnipprophet.io/?prices=108.95.90.86.81&first=yes&pattern=small-spike (pattern and first are optional)

Oh, that's a perfect idea. Thank you so much!

**Comment by mikebryant** [comment]
@zhuoweiz I see you've added that feature - got a bug report for you though, if I will in just today's prices, it sends them to turnipprophet.io as if it were the start of the week - you need to insert padding, i.e. leave blank values for Sunday's price etc.

**Comment by Shamus03** [comment]
That doesn't seem like a bug.  It makes sense that to populate one price in the middle of the week you need to put blank spaces for the previous days.  For example to fill just Thursday evening's price: https://turnipprophet.io/?prices=........81&first=yes&pattern=small-spike

**Comment by zhuoweiz** [comment]
> @zhuoweiz I see you've added that feature - got a bug report for you though, if I will in just today's prices, it sends them to turnipprophet.io as if it were the start of the week - you need to insert padding, i.e. leave blank values for Sunday's price etc.

Yeah, I noticed the issue. I am working on it.

**Comment by zhuoweiz** [comment]
> That doesn't seem like a bug. It makes sense that to populate one price in the middle of the week you need to put blank spaces for the previous days. For example to fill just Thursday evening's price: https://turnipprophet.io/?prices=........81&first=yes&pattern=small-spike

correct, but I didn't use blank space in my autofill feature.
